#!/bin/sh
#
# $Id$

set -e

echo "Setting up your build system..."
if [ ! -f doc/ChangeLog ]; then
	touch doc/ChangeLog
fi

# Debian's automake 1.7 does not provide /usr/bin/automake.  *sigh*
if command -v automake-1.7 > /dev/null 2>&1; then
	DEBFUCKUP="-1.7"
else
	DEBFUCKUP=""
fi

aclocal${DEBFUCKUP}
autoheader
automake${DEBFUCKUP} --add-missing
autoconf
echo "Okay, you should be able to run ./configure now."

