/*
	$RCSfile$

	Copyright (C) 1996-1997  Id Software, Inc.

	This program is free software; you can redistribute it and/or
	modify it under the terms of the GNU General Public License
	as published by the Free Software Foundation; either version 2
	of the License, or (at your option) any later version.

	This program is distributed in the hope that it will be useful,
	but WITHOUT ANY WARRANTY; without even the implied warranty of
	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  

	See the GNU General Public License for more details.

	You should have received a copy of the GNU General Public License
	along with this program; if not, write to:
	
		Free Software Foundation, Inc.
		59 Temple Place - Suite 330
		Boston, MA  02111-1307, USA

	$Id$
*/

#ifndef __PROGSVM_H
#define __PROGSVM_H

#include "common.h"
#include "pr_comp.h"					// defs shared with qcc
#include "progdefs.h"					// generated by program cdefs

char *PRVM_GetString(int num);
int PRVM_SetQCString(char *s);
int PRVM_SetEngineString(char *s);
char *PRVM_AllocString(int bufferlength);
void PRVM_FreeString(char *s);

#endif // __PROGSVM_H

