/*
    $RCSfile$

    Copyright (C) 1999-2000  Brian Paul.
    Copyright (C) 2001       Zephaniah E. Hull.

    This program is free software; you can redistribute it and/or
    modify it under the terms of the GNU General Public License
    as published by the Free Software Foundation; either version 2
    of the License, or (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  

    See the GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with this program; if not, write to:

        Free Software Foundation, Inc.
        59 Temple Place - Suite 330
        Boston, MA  02111-1307, USA

    $Id$
*/

#ifndef TWIGL_DONT_NEED
#define TWIGL_DONT_NEED(ret, func, params)
#define UNDEF_TWIGL_DONT_NEED
#endif

#ifndef TWIGL_NEED
#define TWIGL_NEED(ret, func, params)
#define UNDEF_TWIGL_NEED
#endif

#ifndef TWIGL_EXT_DONT_WANT
#define TWIGL_EXT_DONT_WANT(ret, func, params)
#define UNDEF_TWIGL_EXT_DONT_WANT
#endif

#ifndef TWIGL_EXT_WANT
#define TWIGL_EXT_WANT(ret, func, params)
#define UNDEF_TWIGL_EXT_WANT
#endif

TWIGL_DONT_NEED (void, glAccum, (GLenum op, GLfloat value));
TWIGL_EXT_WANT (void, glActiveTextureARB, (GLenum));
TWIGL_DONT_NEED (void, glAlphaFunc, (GLenum func, GLclampf ref));
TWIGL_EXT_DONT_WANT (void, glApplyTextureEXT, (GLenum));
TWIGL_DONT_NEED (GLboolean, glAreTexturesResident, (GLsizei n, const GLuint * textures, GLboolean * residences));
TWIGL_EXT_DONT_WANT (GLboolean, glAreTexturesResidentEXT, (GLsizei, const GLuint *, GLboolean *));
TWIGL_DONT_NEED (void, glArrayElement, (GLint i));
TWIGL_EXT_DONT_WANT (void, glArrayElementEXT, (GLint));
TWIGL_EXT_DONT_WANT (void, glAsyncMarkerSGIX, (GLuint));
TWIGL_NEED (void, glBegin, (GLenum mode));
TWIGL_NEED (void, glBindTexture, (GLenum target, GLuint texture));
TWIGL_EXT_DONT_WANT (void, glBindTextureEXT, (GLenum, GLuint));
TWIGL_EXT_DONT_WANT (void, glBinormal3bEXT, (GLbyte, GLbyte, GLbyte));
TWIGL_EXT_DONT_WANT (void, glBinormal3bvEXT, (const GLbyte *));
TWIGL_EXT_DONT_WANT (void, glBinormal3dEXT, (GLdouble, GLdouble, GLdouble));
TWIGL_EXT_DONT_WANT (void, glBinormal3dvEXT, (const GLdouble *));
TWIGL_EXT_DONT_WANT (void, glBinormal3fEXT, (GLfloat, GLfloat, GLfloat));
TWIGL_EXT_DONT_WANT (void, glBinormal3fvEXT, (const GLfloat *));
TWIGL_EXT_DONT_WANT (void, glBinormal3iEXT, (GLint, GLint, GLint));
TWIGL_EXT_DONT_WANT (void, glBinormal3ivEXT, (const GLint *));
TWIGL_EXT_DONT_WANT (void, glBinormal3sEXT, (GLshort, GLshort, GLshort));
TWIGL_EXT_DONT_WANT (void, glBinormal3svEXT, (const GLshort *));
TWIGL_EXT_DONT_WANT (void, glBinormalPointerEXT, (GLenum, GLsizei, const GLvoid *));
TWIGL_DONT_NEED (void, glBitmap, (GLsizei width, GLsizei height, GLfloat xorig, GLfloat yorig, GLfloat xmove, GLfloat ymove, const GLubyte * bitmap));
TWIGL_DONT_NEED (void, glBlendColor, (GLclampf, GLclampf, GLclampf, GLclampf));
TWIGL_EXT_DONT_WANT (void, glBlendColorEXT, (GLclampf, GLclampf, GLclampf, GLclampf));
TWIGL_DONT_NEED (void, glBlendEquation, (GLenum));
TWIGL_EXT_DONT_WANT (void, glBlendEquationEXT, (GLenum));
TWIGL_NEED (void, glBlendFunc, (GLenum sfactor, GLenum dfactor));
TWIGL_EXT_DONT_WANT (void, glBlendFuncSeparateEXT, (GLenum, GLenum, GLenum, GLenum));
TWIGL_DONT_NEED (void, glCallList, (GLuint list));
TWIGL_DONT_NEED (void, glCallLists, (GLsizei n, GLenum type, const GLvoid * lists));
TWIGL_NEED (void, glClear, (GLbitfield mask));
TWIGL_DONT_NEED (void, glClearAccum, (GLfloat red, GLfloat green, GLfloat blue, GLfloat alpha));
TWIGL_NEED (void, glClearColor, (GLclampf red, GLclampf green, GLclampf blue, GLclampf alpha));
TWIGL_DONT_NEED (void, glClearDepth, (GLclampd depth));
TWIGL_DONT_NEED (void, glClearIndex, (GLfloat c));
TWIGL_DONT_NEED (void, glClearStencil, (GLint s));
TWIGL_EXT_DONT_WANT (void, glClientActiveTextureARB, (GLenum));
TWIGL_DONT_NEED (void, glClipPlane, (GLenum plane, const GLdouble * equation));
TWIGL_DONT_NEED (void, glColor3b, (GLbyte red, GLbyte green, GLbyte blue));
TWIGL_DONT_NEED (void, glColor3bv, (const GLbyte * v));
TWIGL_DONT_NEED (void, glColor3d, (GLdouble red, GLdouble green, GLdouble blue));
TWIGL_DONT_NEED (void, glColor3dv, (const GLdouble * v));
TWIGL_NEED (void, glColor3f, (GLfloat red, GLfloat green, GLfloat blue));
TWIGL_EXT_DONT_WANT (void, glColor3fVertex3fSUN, (GLfloat, GLfloat, GLfloat, GLfloat, GLfloat, GLfloat));
TWIGL_EXT_DONT_WANT (void, glColor3fVertex3fvSUN, (const GLfloat *, const GLfloat *));
TWIGL_NEED (void, glColor3fv, (const GLfloat * v));
TWIGL_DONT_NEED (void, glColor3i, (GLint red, GLint green, GLint blue));
TWIGL_DONT_NEED (void, glColor3iv, (const GLint * v));
TWIGL_DONT_NEED (void, glColor3s, (GLshort red, GLshort green, GLshort blue));
TWIGL_DONT_NEED (void, glColor3sv, (const GLshort * v));
TWIGL_DONT_NEED (void, glColor3ub, (GLubyte red, GLubyte green, GLubyte blue));
TWIGL_NEED (void, glColor3ubv, (const GLubyte * v));
TWIGL_DONT_NEED (void, glColor3ui, (GLuint red, GLuint green, GLuint blue));
TWIGL_DONT_NEED (void, glColor3uiv, (const GLuint * v));
TWIGL_DONT_NEED (void, glColor3us, (GLushort red, GLushort green, GLushort blue));
TWIGL_DONT_NEED (void, glColor3usv, (const GLushort * v));
TWIGL_DONT_NEED (void, glColor4b, (GLbyte red, GLbyte green, GLbyte blue, GLbyte alpha));
TWIGL_DONT_NEED (void, glColor4bv, (const GLbyte * v));
TWIGL_DONT_NEED (void, glColor4d, (GLdouble red, GLdouble green, GLdouble blue, GLdouble alpha));
TWIGL_DONT_NEED (void, glColor4dv, (const GLdouble * v));
TWIGL_NEED (void, glColor4f, (GLfloat red, GLfloat green, GLfloat blue, GLfloat alpha));
TWIGL_EXT_DONT_WANT (void, glColor4fNormal3fVertex3fSUN, (GLfloat, GLfloat, GLfloat, GLfloat, GLfloat, GLfloat, GLfloat, GLfloat, GLfloat, GLfloat));
TWIGL_EXT_DONT_WANT (void, glColor4fNormal3fVertex3fvSUN, (const GLfloat *, const GLfloat *, const GLfloat *));
TWIGL_NEED (void, glColor4fv, (const GLfloat * v));
TWIGL_DONT_NEED (void, glColor4i, (GLint red, GLint green, GLint blue, GLint alpha));
TWIGL_DONT_NEED (void, glColor4iv, (const GLint * v));
TWIGL_DONT_NEED (void, glColor4s, (GLshort red, GLshort green, GLshort blue, GLshort alpha));
TWIGL_DONT_NEED (void, glColor4sv, (const GLshort * v));
TWIGL_NEED (void, glColor4ub, (GLubyte red, GLubyte green, GLubyte blue, GLubyte alpha));
TWIGL_EXT_DONT_WANT (void, glColor4ubVertex2fSUN, (GLubyte, GLubyte, GLubyte, GLubyte, GLfloat, GLfloat));
TWIGL_EXT_DONT_WANT (void, glColor4ubVertex2fvSUN, (const GLubyte *, const GLfloat *));
TWIGL_EXT_DONT_WANT (void, glColor4ubVertex3fSUN, (GLubyte, GLubyte, GLubyte, GLubyte, GLfloat, GLfloat, GLfloat));
TWIGL_EXT_DONT_WANT (void, glColor4ubVertex3fvSUN, (const GLubyte *, const GLfloat *));
TWIGL_NEED (void, glColor4ubv, (const GLubyte * v));
TWIGL_DONT_NEED (void, glColor4ui, (GLuint red, GLuint green, GLuint blue, GLuint alpha));
TWIGL_DONT_NEED (void, glColor4uiv, (const GLuint * v));
TWIGL_DONT_NEED (void, glColor4us, (GLushort red, GLushort green, GLushort blue, GLushort alpha));
TWIGL_DONT_NEED (void, glColor4usv, (const GLushort * v));
TWIGL_DONT_NEED (void, glColorMask, (GLboolean red, GLboolean green, GLboolean blue, GLboolean alpha));
TWIGL_DONT_NEED (void, glColorMaterial, (GLenum face, GLenum mode));
TWIGL_DONT_NEED (void, glColorPointer, (GLint size, GLenum type, GLsizei stride, const GLvoid * ptr));
TWIGL_EXT_DONT_WANT (void, glColorPointerEXT, (GLint, GLenum, GLsizei, GLsizei, const GLvoid *));
TWIGL_EXT_DONT_WANT (void, glColorPointerListIBM, (GLint, GLenum, GLint, const GLvoid * *, GLint));
TWIGL_EXT_DONT_WANT (void, glColorPointervINTEL, (GLint, GLenum, const GLvoid * *));
TWIGL_DONT_NEED (void, glColorSubTable, (GLenum, GLsizei, GLsizei, GLenum, GLenum, const GLvoid *));
TWIGL_EXT_DONT_WANT (void, glColorSubTableEXT, (GLenum, GLsizei, GLsizei, GLenum, GLenum, const GLvoid *));
TWIGL_DONT_NEED (void, glColorTable, (GLenum, GLenum, GLsizei, GLenum, GLenum, const GLvoid *));
TWIGL_EXT_DONT_WANT (void, glColorTableEXT, (GLenum, GLenum, GLsizei, GLenum, GLenum, const GLvoid *));
TWIGL_DONT_NEED (void, glColorTableParameterfv, (GLenum, GLenum, const GLfloat *));
TWIGL_EXT_DONT_WANT (void, glColorTableParameterfvSGI, (GLenum, GLenum, const GLfloat *));
TWIGL_DONT_NEED (void, glColorTableParameteriv, (GLenum, GLenum, const GLint *));
TWIGL_EXT_DONT_WANT (void, glColorTableParameterivSGI, (GLenum, GLenum, const GLint *));
TWIGL_EXT_DONT_WANT (void, glColorTableSGI, (GLenum, GLenum, GLsizei, GLenum, GLenum, const GLvoid *));
TWIGL_EXT_DONT_WANT (void, glCombinerInputNV, (GLenum, GLenum, GLenum, GLenum, GLenum, GLenum));
TWIGL_EXT_DONT_WANT (void, glCombinerOutputNV, (GLenum, GLenum, GLenum, GLenum, GLenum, GLenum, GLenum, GLboolean, GLboolean, GLboolean));
TWIGL_EXT_DONT_WANT (void, glCombinerParameterfNV, (GLenum, GLfloat));
TWIGL_EXT_DONT_WANT (void, glCombinerParameterfvNV, (GLenum, const GLfloat *));
TWIGL_EXT_DONT_WANT (void, glCombinerParameteriNV, (GLenum, GLint));
TWIGL_EXT_DONT_WANT (void, glCombinerParameterivNV, (GLenum, const GLint *));
TWIGL_EXT_DONT_WANT (void, glCompressedTexImage1DARB, (GLenum, GLint, GLenum, GLsizei, GLint, GLsizei, const GLvoid *));
TWIGL_EXT_DONT_WANT (void, glCompressedTexImage2DARB, (GLenum, GLint, GLenum, GLsizei, GLsizei, GLint, GLsizei, const GLvoid *));
TWIGL_EXT_DONT_WANT (void, glCompressedTexImage3DARB, (GLenum, GLint, GLenum, GLsizei, GLsizei, GLsizei, GLint, GLsizei, const GLvoid *));
TWIGL_EXT_DONT_WANT (void, glCompressedTexSubImage1DARB, (GLenum, GLint, GLint, GLsizei, GLenum, GLsizei, const GLvoid *));
TWIGL_EXT_DONT_WANT (void, glCompressedTexSubImage2DARB, (GLenum, GLint, GLint, GLint, GLsizei, GLsizei, GLenum, GLsizei, const GLvoid *));
TWIGL_EXT_DONT_WANT (void, glCompressedTexSubImage3DARB, (GLenum, GLint, GLint, GLint, GLint, GLsizei, GLsizei, GLsizei, GLenum, GLsizei, const GLvoid *));
TWIGL_DONT_NEED (void, glConvolutionFilter1D, (GLenum, GLenum, GLsizei, GLenum, GLenum, const GLvoid *));
TWIGL_EXT_DONT_WANT (void, glConvolutionFilter1DEXT, (GLenum, GLenum, GLsizei, GLenum, GLenum, const GLvoid *));
TWIGL_DONT_NEED (void, glConvolutionFilter2D, (GLenum, GLenum, GLsizei, GLsizei, GLenum, GLenum, const GLvoid *));
TWIGL_EXT_DONT_WANT (void, glConvolutionFilter2DEXT, (GLenum, GLenum, GLsizei, GLsizei, GLenum, GLenum, const GLvoid *));
TWIGL_DONT_NEED (void, glConvolutionParameterf, (GLenum, GLenum, GLfloat));
TWIGL_EXT_DONT_WANT (void, glConvolutionParameterfEXT, (GLenum, GLenum, GLfloat));
TWIGL_DONT_NEED (void, glConvolutionParameterfv, (GLenum, GLenum, const GLfloat *));
TWIGL_EXT_DONT_WANT (void, glConvolutionParameterfvEXT, (GLenum, GLenum, const GLfloat *));
TWIGL_DONT_NEED (void, glConvolutionParameteri, (GLenum, GLenum, GLint));
TWIGL_EXT_DONT_WANT (void, glConvolutionParameteriEXT, (GLenum, GLenum, GLint));
TWIGL_DONT_NEED (void, glConvolutionParameteriv, (GLenum, GLenum, const GLint *));
TWIGL_EXT_DONT_WANT (void, glConvolutionParameterivEXT, (GLenum, GLenum, const GLint *));
TWIGL_DONT_NEED (void, glCopyColorSubTable, (GLenum, GLsizei, GLint, GLint, GLsizei));
TWIGL_EXT_DONT_WANT (void, glCopyColorSubTableEXT, (GLenum, GLsizei, GLint, GLint, GLsizei));
TWIGL_DONT_NEED (void, glCopyColorTable, (GLenum, GLenum, GLint, GLint, GLsizei));
TWIGL_EXT_DONT_WANT (void, glCopyColorTableSGI, (GLenum, GLenum, GLint, GLint, GLsizei));
TWIGL_DONT_NEED (void, glCopyConvolutionFilter1D, (GLenum, GLenum, GLint, GLint, GLsizei));
TWIGL_EXT_DONT_WANT (void, glCopyConvolutionFilter1DEXT, (GLenum, GLenum, GLint, GLint, GLsizei));
TWIGL_DONT_NEED (void, glCopyConvolutionFilter2D, (GLenum, GLenum, GLint, GLint, GLsizei, GLsizei));
TWIGL_EXT_DONT_WANT (void, glCopyConvolutionFilter2DEXT, (GLenum, GLenum, GLint, GLint, GLsizei, GLsizei));
TWIGL_DONT_NEED (void, glCopyPixels, (GLint x, GLint y, GLsizei width, GLsizei height, GLenum type));
TWIGL_DONT_NEED (void, glCopyTexImage1D, (GLenum target, GLint level, GLenum internalformat, GLint x, GLint y, GLsizei width, GLint border));
TWIGL_EXT_DONT_WANT (void, glCopyTexImage1DEXT, (GLenum, GLint, GLenum, GLint, GLint, GLsizei, GLint));
TWIGL_DONT_NEED (void, glCopyTexImage2D, (GLenum target, GLint level, GLenum internalformat, GLint x, GLint y, GLsizei width, GLsizei height, GLint border));
TWIGL_EXT_DONT_WANT (void, glCopyTexImage2DEXT, (GLenum, GLint, GLenum, GLint, GLint, GLsizei, GLsizei, GLint));
TWIGL_DONT_NEED (void, glCopyTexSubImage1D, (GLenum target, GLint level, GLint xoffset, GLint x, GLint y, GLsizei width));
TWIGL_EXT_DONT_WANT (void, glCopyTexSubImage1DEXT, (GLenum, GLint, GLint, GLint, GLint, GLsizei));
TWIGL_DONT_NEED (void, glCopyTexSubImage2D, (GLenum target, GLint level, GLint xoffset, GLint yoffset, GLint x, GLint y, GLsizei width, GLsizei height));
TWIGL_EXT_DONT_WANT (void, glCopyTexSubImage2DEXT, (GLenum, GLint, GLint, GLint, GLint, GLint, GLsizei, GLsizei));
TWIGL_DONT_NEED (void, glCopyTexSubImage3D, (GLenum, GLint, GLint, GLint, GLint, GLint, GLint, GLsizei, GLsizei));
TWIGL_EXT_DONT_WANT (void, glCopyTexSubImage3DEXT, (GLenum, GLint, GLint, GLint, GLint, GLint, GLint, GLsizei, GLsizei));
TWIGL_NEED (void, glCullFace, (GLenum mode));
TWIGL_EXT_DONT_WANT (void, glCullParameterdvEXT, (GLenum, GLdouble *));
TWIGL_EXT_DONT_WANT (void, glCullParameterfvEXT, (GLenum, GLfloat *));
TWIGL_EXT_DONT_WANT (void, glDeformSGIX, (GLbitfield));
TWIGL_EXT_DONT_WANT (void, glDeformationMap3dSGIX, (GLenum, GLdouble, GLdouble, GLint, GLint, GLdouble, GLdouble, GLint, GLint, GLdouble, GLdouble, GLint, GLint, const GLdouble *));
TWIGL_EXT_DONT_WANT (void, glDeformationMap3fSGIX, (GLenum, GLfloat, GLfloat, GLint, GLint, GLfloat, GLfloat, GLint, GLint, GLfloat, GLfloat, GLint, GLint, const GLfloat *));
TWIGL_EXT_DONT_WANT (void, glDeleteAsyncMarkersSGIX, (GLuint, GLsizei));
TWIGL_DONT_NEED (void, glDeleteLists, (GLuint list, GLsizei range));
TWIGL_DONT_NEED (void, glDeleteTextures, (GLsizei n, const GLuint * textures));
TWIGL_EXT_DONT_WANT (void, glDeleteTexturesEXT, (GLsizei, const GLuint *));
TWIGL_NEED (void, glDepthFunc, (GLenum func));
TWIGL_NEED (void, glDepthMask, (GLboolean flag));
TWIGL_NEED (void, glDepthRange, (GLclampd near_val, GLclampd far_val));
TWIGL_EXT_DONT_WANT (void, glDetailTexFuncSGIS, (GLenum, GLsizei, const GLfloat *));
TWIGL_NEED (void, glDisable, (GLenum cap));
TWIGL_DONT_NEED (void, glDisableClientState, (GLenum cap));
TWIGL_EXT_DONT_WANT (void, glDisableTraceMESA, (GLbitfield mask));
TWIGL_DONT_NEED (void, glDrawArrays, (GLenum mode, GLint first, GLsizei count));
TWIGL_EXT_DONT_WANT (void, glDrawArraysEXT, (GLenum, GLint, GLsizei));
TWIGL_NEED (void, glDrawBuffer, (GLenum mode));
TWIGL_DONT_NEED (void, glDrawElements, (GLenum mode, GLsizei count, GLenum type, const GLvoid * indices));
TWIGL_DONT_NEED (void, glDrawPixels, (GLsizei width, GLsizei height, GLenum format, GLenum type, const GLvoid * pixels));
TWIGL_DONT_NEED (void, glDrawRangeElements, (GLenum, GLuint, GLuint, GLsizei, GLenum, const GLvoid *));
TWIGL_EXT_DONT_WANT (void, glDrawRangeElementsEXT, (GLenum, GLuint, GLuint, GLsizei, GLenum, const GLvoid *));
TWIGL_DONT_NEED (void, glEdgeFlag, (GLboolean flag));
TWIGL_DONT_NEED (void, glEdgeFlagPointer, (GLsizei stride, const GLvoid * ptr));
TWIGL_EXT_DONT_WANT (void, glEdgeFlagPointerEXT, (GLsizei, GLsizei, const GLboolean *));
TWIGL_EXT_DONT_WANT (void, glEdgeFlagPointerListIBM, (GLint, const GLboolean * *, GLint));
TWIGL_DONT_NEED (void, glEdgeFlagv, (const GLboolean * flag));
TWIGL_NEED (void, glEnable, (GLenum cap));
TWIGL_DONT_NEED (void, glEnableClientState, (GLenum cap));
TWIGL_EXT_DONT_WANT (void, glEnableTraceMESA, (GLbitfield mask));
TWIGL_NEED (void, glEnd, (void));
TWIGL_DONT_NEED (void, glEndList, (void));
TWIGL_EXT_DONT_WANT (void, glEndTraceMESA, (void));
TWIGL_DONT_NEED (void, glEvalCoord1d, (GLdouble u));
TWIGL_DONT_NEED (void, glEvalCoord1dv, (const GLdouble * u));
TWIGL_DONT_NEED (void, glEvalCoord1f, (GLfloat u));
TWIGL_DONT_NEED (void, glEvalCoord1fv, (const GLfloat * u));
TWIGL_DONT_NEED (void, glEvalCoord2d, (GLdouble u, GLdouble v));
TWIGL_DONT_NEED (void, glEvalCoord2dv, (const GLdouble * u));
TWIGL_DONT_NEED (void, glEvalCoord2f, (GLfloat u, GLfloat v));
TWIGL_DONT_NEED (void, glEvalCoord2fv, (const GLfloat * u));
TWIGL_DONT_NEED (void, glEvalMesh1, (GLenum mode, GLint i1, GLint i2));
TWIGL_DONT_NEED (void, glEvalMesh2, (GLenum mode, GLint i1, GLint i2, GLint j1, GLint j2));
TWIGL_DONT_NEED (void, glEvalPoint1, (GLint i));
TWIGL_DONT_NEED (void, glEvalPoint2, (GLint i, GLint j));
TWIGL_DONT_NEED (void, glFeedbackBuffer, (GLsizei size, GLenum type, GLfloat * buffer));
TWIGL_EXT_DONT_WANT (void, glFinalCombinerInputNV, (GLenum, GLenum, GLenum, GLenum));
TWIGL_NEED (void, glFinish, (void));
TWIGL_EXT_DONT_WANT (GLint, glFinishAsyncSGIX, (GLuint *));
TWIGL_EXT_DONT_WANT (void, glFinishTextureSUNX, (void));
TWIGL_DONT_NEED (void, glFlush, (void));
TWIGL_EXT_DONT_WANT (void, glFlushRasterSGIX, (void));
TWIGL_EXT_DONT_WANT (void, glFlushVertexArrayRangeNV, (void));
TWIGL_EXT_DONT_WANT (void, glFogCoordPointerEXT, (GLenum, GLsizei, const GLvoid *));
TWIGL_EXT_DONT_WANT (void, glFogCoordPointerListIBM, (GLenum, GLint, const GLvoid * *, GLint));
TWIGL_EXT_DONT_WANT (void, glFogCoorddEXT, (GLdouble));
TWIGL_EXT_DONT_WANT (void, glFogCoorddvEXT, (const GLdouble *));
TWIGL_EXT_DONT_WANT (void, glFogCoordfEXT, (GLfloat));
TWIGL_EXT_DONT_WANT (void, glFogCoordfvEXT, (const GLfloat *));
TWIGL_EXT_DONT_WANT (void, glFogFuncSGIS, (GLsizei, const GLfloat *));
TWIGL_NEED (void, glFogf, (GLenum pname, GLfloat param));
TWIGL_NEED (void, glFogfv, (GLenum pname, const GLfloat * params));
TWIGL_NEED (void, glFogi, (GLenum pname, GLint param));
TWIGL_DONT_NEED (void, glFogiv, (GLenum pname, const GLint * params));
TWIGL_EXT_DONT_WANT (void, glFragmentColorMaterialSGIX, (GLenum, GLenum));
TWIGL_EXT_DONT_WANT (void, glFragmentLightModelfSGIX, (GLenum, GLfloat));
TWIGL_EXT_DONT_WANT (void, glFragmentLightModelfvSGIX, (GLenum, const GLfloat *));
TWIGL_EXT_DONT_WANT (void, glFragmentLightModeliSGIX, (GLenum, GLint));
TWIGL_EXT_DONT_WANT (void, glFragmentLightModelivSGIX, (GLenum, const GLint *));
TWIGL_EXT_DONT_WANT (void, glFragmentLightfSGIX, (GLenum, GLenum, GLfloat));
TWIGL_EXT_DONT_WANT (void, glFragmentLightfvSGIX, (GLenum, GLenum, const GLfloat *));
TWIGL_EXT_DONT_WANT (void, glFragmentLightiSGIX, (GLenum, GLenum, GLint));
TWIGL_EXT_DONT_WANT (void, glFragmentLightivSGIX, (GLenum, GLenum, const GLint *));
TWIGL_EXT_DONT_WANT (void, glFragmentMaterialfSGIX, (GLenum, GLenum, GLfloat));
TWIGL_EXT_DONT_WANT (void, glFragmentMaterialfvSGIX, (GLenum, GLenum, const GLfloat *));
TWIGL_EXT_DONT_WANT (void, glFragmentMaterialiSGIX, (GLenum, GLenum, GLint));
TWIGL_EXT_DONT_WANT (void, glFragmentMaterialivSGIX, (GLenum, GLenum, const GLint *));
TWIGL_EXT_DONT_WANT (void, glFrameZoomSGIX, (GLint));
TWIGL_DONT_NEED (void, glFrontFace, (GLenum mode));
TWIGL_NEED (void, glFrustum, (GLdouble left, GLdouble right, GLdouble bottom, GLdouble top, GLdouble near_val, GLdouble far_val));
TWIGL_EXT_DONT_WANT (GLuint, glGenAsyncMarkersSGIX, (GLsizei));
TWIGL_DONT_NEED (GLuint, glGenLists, (GLsizei range));
TWIGL_DONT_NEED (void, glGenTextures, (GLsizei n, GLuint * textures));
TWIGL_EXT_DONT_WANT (void, glGenTexturesEXT, (GLsizei, GLuint *));
TWIGL_DONT_NEED (void, glGetBooleanv, (GLenum pname, GLboolean * params));
TWIGL_DONT_NEED (void, glGetClipPlane, (GLenum plane, GLdouble * equation));
TWIGL_DONT_NEED (void, glGetColorTable, (GLenum, GLenum, GLenum, GLvoid *));
TWIGL_EXT_DONT_WANT (void, glGetColorTableEXT, (GLenum, GLenum, GLenum, GLvoid *));
TWIGL_DONT_NEED (void, glGetColorTableParameterfv, (GLenum, GLenum, GLfloat *));
TWIGL_EXT_DONT_WANT (void, glGetColorTableParameterfvEXT, (GLenum, GLenum, GLfloat *));
TWIGL_EXT_DONT_WANT (void, glGetColorTableParameterfvSGI, (GLenum, GLenum, GLfloat *));
TWIGL_DONT_NEED (void, glGetColorTableParameteriv, (GLenum, GLenum, GLint *));
TWIGL_EXT_DONT_WANT (void, glGetColorTableParameterivEXT, (GLenum, GLenum, GLint *));
TWIGL_EXT_DONT_WANT (void, glGetColorTableParameterivSGI, (GLenum, GLenum, GLint *));
TWIGL_EXT_DONT_WANT (void, glGetColorTableSGI, (GLenum, GLenum, GLenum, GLvoid *));
TWIGL_EXT_DONT_WANT (void, glGetCombinerInputParameterfvNV, (GLenum, GLenum, GLenum, GLenum, GLfloat *));
TWIGL_EXT_DONT_WANT (void, glGetCombinerInputParameterivNV, (GLenum, GLenum, GLenum, GLenum, GLint *));
TWIGL_EXT_DONT_WANT (void, glGetCombinerOutputParameterfvNV, (GLenum, GLenum, GLenum, GLfloat *));
TWIGL_EXT_DONT_WANT (void, glGetCombinerOutputParameterivNV, (GLenum, GLenum, GLenum, GLint *));
TWIGL_EXT_DONT_WANT (void, glGetCompressedTexImageARB, (GLenum, GLint, void *));
TWIGL_DONT_NEED (void, glGetConvolutionFilter, (GLenum, GLenum, GLenum, GLvoid *));
TWIGL_EXT_DONT_WANT (void, glGetConvolutionFilterEXT, (GLenum, GLenum, GLenum, GLvoid *));
TWIGL_DONT_NEED (void, glGetConvolutionParameterfv, (GLenum, GLenum, GLfloat *));
TWIGL_EXT_DONT_WANT (void, glGetConvolutionParameterfvEXT, (GLenum, GLenum, GLfloat *));
TWIGL_DONT_NEED (void, glGetConvolutionParameteriv, (GLenum, GLenum, GLint *));
TWIGL_EXT_DONT_WANT (void, glGetConvolutionParameterivEXT, (GLenum, GLenum, GLint *));
TWIGL_EXT_DONT_WANT (void, glGetDetailTexFuncSGIS, (GLenum, GLfloat *));
TWIGL_DONT_NEED (void, glGetDoublev, (GLenum pname, GLdouble * params));
TWIGL_DONT_NEED (GLenum, glGetError, (void));
TWIGL_EXT_DONT_WANT (void, glGetFinalCombinerInputParameterfvNV, (GLenum, GLenum, GLfloat *));
TWIGL_EXT_DONT_WANT (void, glGetFinalCombinerInputParameterivNV, (GLenum, GLenum, GLint *));
TWIGL_NEED (void, glGetFloatv, (GLenum pname, GLfloat * params));
TWIGL_EXT_DONT_WANT (void, glGetFogFuncSGIS, (const GLfloat *));
TWIGL_EXT_DONT_WANT (void, glGetFragmentLightfvSGIX, (GLenum, GLenum, GLfloat *));
TWIGL_EXT_DONT_WANT (void, glGetFragmentLightivSGIX, (GLenum, GLenum, GLint *));
TWIGL_EXT_DONT_WANT (void, glGetFragmentMaterialfvSGIX, (GLenum, GLenum, GLfloat *));
TWIGL_EXT_DONT_WANT (void, glGetFragmentMaterialivSGIX, (GLenum, GLenum, GLint *));
TWIGL_DONT_NEED (void, glGetHistogram, (GLenum, GLboolean, GLenum, GLenum, GLvoid *));
TWIGL_EXT_DONT_WANT (void, glGetHistogramEXT, (GLenum, GLboolean, GLenum, GLenum, GLvoid *));
TWIGL_DONT_NEED (void, glGetHistogramParameterfv, (GLenum, GLenum, GLfloat *));
TWIGL_EXT_DONT_WANT (void, glGetHistogramParameterfvEXT, (GLenum, GLenum, GLfloat *));
TWIGL_DONT_NEED (void, glGetHistogramParameteriv, (GLenum, GLenum, GLint *));
TWIGL_EXT_DONT_WANT (void, glGetHistogramParameterivEXT, (GLenum, GLenum, GLint *));
TWIGL_EXT_DONT_WANT (void, glGetImageTransformParameterfvHP, (GLenum, GLenum, GLfloat *));
TWIGL_EXT_DONT_WANT (void, glGetImageTransformParameterivHP, (GLenum, GLenum, GLint *));
TWIGL_EXT_DONT_WANT (GLint, glGetInstrumentsSGIX, (void));
TWIGL_NEED (void, glGetIntegerv, (GLenum pname, GLint * params));
TWIGL_DONT_NEED (void, glGetLightfv, (GLenum light, GLenum pname, GLfloat * params));
TWIGL_DONT_NEED (void, glGetLightiv, (GLenum light, GLenum pname, GLint * params));
TWIGL_EXT_DONT_WANT (void, glGetListParameterfvSGIX, (GLuint, GLenum, GLfloat *));
TWIGL_EXT_DONT_WANT (void, glGetListParameterivSGIX, (GLuint, GLenum, GLint *));
TWIGL_DONT_NEED (void, glGetMapdv, (GLenum target, GLenum query, GLdouble * v));
TWIGL_DONT_NEED (void, glGetMapfv, (GLenum target, GLenum query, GLfloat * v));
TWIGL_DONT_NEED (void, glGetMapiv, (GLenum target, GLenum query, GLint * v));
TWIGL_DONT_NEED (void, glGetMaterialfv, (GLenum face, GLenum pname, GLfloat * params));
TWIGL_DONT_NEED (void, glGetMaterialiv, (GLenum face, GLenum pname, GLint * params));
TWIGL_DONT_NEED (void, glGetMinmax, (GLenum, GLboolean, GLenum, GLenum, GLvoid *));
TWIGL_EXT_DONT_WANT (void, glGetMinmaxEXT, (GLenum, GLboolean, GLenum, GLenum, GLvoid *));
TWIGL_DONT_NEED (void, glGetMinmaxParameterfv, (GLenum, GLenum, GLfloat *));
TWIGL_EXT_DONT_WANT (void, glGetMinmaxParameterfvEXT, (GLenum, GLenum, GLfloat *));
TWIGL_DONT_NEED (void, glGetMinmaxParameteriv, (GLenum, GLenum, GLint *));
TWIGL_EXT_DONT_WANT (void, glGetMinmaxParameterivEXT, (GLenum, GLenum, GLint *));
TWIGL_DONT_NEED (void, glGetPixelMapfv, (GLenum map, GLfloat * values));
TWIGL_DONT_NEED (void, glGetPixelMapuiv, (GLenum map, GLuint * values));
TWIGL_DONT_NEED (void, glGetPixelMapusv, (GLenum map, GLushort * values));
TWIGL_EXT_DONT_WANT (void, glGetPixelTexGenParameterfvSGIS, (GLenum, GLfloat *));
TWIGL_EXT_DONT_WANT (void, glGetPixelTexGenParameterivSGIS, (GLenum, GLint *));
TWIGL_DONT_NEED (void, glGetPointerv, (GLenum pname, GLvoid ** params));
TWIGL_EXT_DONT_WANT (void, glGetPointervEXT, (GLenum, GLvoid * *));
TWIGL_DONT_NEED (void, glGetPolygonStipple, (GLubyte * mask));
TWIGL_DONT_NEED (void, glGetSeparableFilter, (GLenum, GLenum, GLenum, GLvoid *, GLvoid *, GLvoid *));
TWIGL_EXT_DONT_WANT (void, glGetSeparableFilterEXT, (GLenum, GLenum, GLenum, GLvoid *, GLvoid *, GLvoid *));
TWIGL_EXT_DONT_WANT (void, glGetSharpenTexFuncSGIS, (GLenum, GLfloat *));
TWIGL_NEED (const GLubyte *, glGetString, (GLenum name));
TWIGL_DONT_NEED (void, glGetTexEnvfv, (GLenum target, GLenum pname, GLfloat * params));
TWIGL_DONT_NEED (void, glGetTexEnviv, (GLenum target, GLenum pname, GLint * params));
TWIGL_EXT_DONT_WANT (void, glGetTexFilterFuncSGIS, (GLenum, GLenum, GLfloat *));
TWIGL_DONT_NEED (void, glGetTexGendv, (GLenum coord, GLenum pname, GLdouble * params));
TWIGL_DONT_NEED (void, glGetTexGenfv, (GLenum coord, GLenum pname, GLfloat * params));
TWIGL_DONT_NEED (void, glGetTexGeniv, (GLenum coord, GLenum pname, GLint * params));
TWIGL_DONT_NEED (void, glGetTexImage, (GLenum target, GLint level, GLenum format, GLenum type, GLvoid * pixels));
TWIGL_DONT_NEED (void, glGetTexLevelParameterfv, (GLenum target, GLint level, GLenum pname, GLfloat * params));
TWIGL_DONT_NEED (void, glGetTexLevelParameteriv, (GLenum target, GLint level, GLenum pname, GLint * params));
TWIGL_DONT_NEED (void, glGetTexParameterfv, (GLenum target, GLenum pname, GLfloat * params));
TWIGL_DONT_NEED (void, glGetTexParameteriv, (GLenum target, GLenum pname, GLint * params));
TWIGL_EXT_DONT_WANT (void, glGlobalAlphaFactorbSUN, (GLbyte));
TWIGL_EXT_DONT_WANT (void, glGlobalAlphaFactordSUN, (GLdouble));
TWIGL_EXT_DONT_WANT (void, glGlobalAlphaFactorfSUN, (GLfloat));
TWIGL_EXT_DONT_WANT (void, glGlobalAlphaFactoriSUN, (GLint));
TWIGL_EXT_DONT_WANT (void, glGlobalAlphaFactorsSUN, (GLshort));
TWIGL_EXT_DONT_WANT (void, glGlobalAlphaFactorubSUN, (GLubyte));
TWIGL_EXT_DONT_WANT (void, glGlobalAlphaFactoruiSUN, (GLuint));
TWIGL_EXT_DONT_WANT (void, glGlobalAlphaFactorusSUN, (GLushort));
TWIGL_NEED (void, glHint, (GLenum target, GLenum mode));
TWIGL_EXT_DONT_WANT (void, glHintPGI, (GLenum, GLint));
TWIGL_DONT_NEED (void, glHistogram, (GLenum, GLsizei, GLenum, GLboolean));
TWIGL_EXT_DONT_WANT (void, glHistogramEXT, (GLenum, GLsizei, GLenum, GLboolean));
TWIGL_EXT_DONT_WANT (void, glIglooInterfaceSGIX, (GLenum, const GLvoid *));
TWIGL_EXT_DONT_WANT (void, glImageTransformParameterfHP, (GLenum, GLenum, GLfloat));
TWIGL_EXT_DONT_WANT (void, glImageTransformParameterfvHP, (GLenum, GLenum, const GLfloat *));
TWIGL_EXT_DONT_WANT (void, glImageTransformParameteriHP, (GLenum, GLenum, GLint));
TWIGL_EXT_DONT_WANT (void, glImageTransformParameterivHP, (GLenum, GLenum, const GLint *));
TWIGL_EXT_DONT_WANT (void, glIndexFuncEXT, (GLenum, GLclampf));
TWIGL_DONT_NEED (void, glIndexMask, (GLuint mask));
TWIGL_EXT_DONT_WANT (void, glIndexMaterialEXT, (GLenum, GLenum));
TWIGL_DONT_NEED (void, glIndexPointer, (GLenum type, GLsizei stride, const GLvoid * ptr));
TWIGL_EXT_DONT_WANT (void, glIndexPointerEXT, (GLenum, GLsizei, GLsizei, const GLvoid *));
TWIGL_EXT_DONT_WANT (void, glIndexPointerListIBM, (GLenum, GLint, const GLvoid * *, GLint));
TWIGL_DONT_NEED (void, glIndexd, (GLdouble c));
TWIGL_DONT_NEED (void, glIndexdv, (const GLdouble * c));
TWIGL_DONT_NEED (void, glIndexf, (GLfloat c));
TWIGL_DONT_NEED (void, glIndexfv, (const GLfloat * c));
TWIGL_DONT_NEED (void, glIndexi, (GLint c));
TWIGL_DONT_NEED (void, glIndexiv, (const GLint * c));
TWIGL_DONT_NEED (void, glIndexs, (GLshort c));
TWIGL_DONT_NEED (void, glIndexsv, (const GLshort * c));
TWIGL_DONT_NEED (void, glIndexub, (GLubyte c));
TWIGL_DONT_NEED (void, glIndexubv, (const GLubyte * c));
TWIGL_DONT_NEED (void, glInitNames, (void));
TWIGL_EXT_DONT_WANT (void, glInstrumentsBufferSGIX, (GLsizei, GLint *));
TWIGL_DONT_NEED (void, glInterleavedArrays, (GLenum format, GLsizei stride, const GLvoid * pointer));
TWIGL_EXT_DONT_WANT (GLboolean, glIsAsyncMarkerSGIX, (GLuint));
TWIGL_DONT_NEED (GLboolean, glIsEnabled, (GLenum cap));
TWIGL_DONT_NEED (GLboolean, glIsList, (GLuint list));
TWIGL_DONT_NEED (GLboolean, glIsTexture, (GLuint texture));
TWIGL_EXT_DONT_WANT (GLboolean, glIsTextureEXT, (GLuint));
TWIGL_EXT_DONT_WANT (void, glLightEnviSGIX, (GLenum, GLint));
TWIGL_DONT_NEED (void, glLightModelf, (GLenum pname, GLfloat param));
TWIGL_DONT_NEED (void, glLightModelfv, (GLenum pname, const GLfloat * params));
TWIGL_DONT_NEED (void, glLightModeli, (GLenum pname, GLint param));
TWIGL_DONT_NEED (void, glLightModeliv, (GLenum pname, const GLint * params));
TWIGL_DONT_NEED (void, glLightf, (GLenum light, GLenum pname, GLfloat param));
TWIGL_DONT_NEED (void, glLightfv, (GLenum light, GLenum pname, const GLfloat * params));
TWIGL_DONT_NEED (void, glLighti, (GLenum light, GLenum pname, GLint param));
TWIGL_DONT_NEED (void, glLightiv, (GLenum light, GLenum pname, const GLint * params));
TWIGL_DONT_NEED (void, glLineStipple, (GLint factor, GLushort pattern));
TWIGL_DONT_NEED (void, glLineWidth, (GLfloat width));
TWIGL_DONT_NEED (void, glListBase, (GLuint base));
TWIGL_EXT_DONT_WANT (void, glListParameterfSGIX, (GLuint, GLenum, GLfloat));
TWIGL_EXT_DONT_WANT (void, glListParameterfvSGIX, (GLuint, GLenum, const GLfloat *));
TWIGL_EXT_DONT_WANT (void, glListParameteriSGIX, (GLuint, GLenum, GLint));
TWIGL_EXT_DONT_WANT (void, glListParameterivSGIX, (GLuint, GLenum, const GLint *));
TWIGL_NEED (void, glLoadIdentity, (void));
TWIGL_EXT_DONT_WANT (void, glLoadIdentityDeformationMapSGIX, (GLbitfield));
TWIGL_DONT_NEED (void, glLoadMatrixd, (const GLdouble * m));
TWIGL_NEED (void, glLoadMatrixf, (const GLfloat * m));
TWIGL_DONT_NEED (void, glLoadName, (GLuint name));
TWIGL_EXT_DONT_WANT (void, glLoadTransposeMatrixdARB, (const GLdouble *));
TWIGL_EXT_DONT_WANT (void, glLoadTransposeMatrixfARB, (const GLfloat *));
TWIGL_EXT_DONT_WANT (void, glLockArraysEXT, (GLint, GLsizei));
TWIGL_DONT_NEED (void, glLogicOp, (GLenum opcode));
TWIGL_DONT_NEED (void, glMap1d, (GLenum target, GLdouble u1, GLdouble u2, GLint stride, GLint order, const GLdouble * points));
TWIGL_DONT_NEED (void, glMap1f, (GLenum target, GLfloat u1, GLfloat u2, GLint stride, GLint order, const GLfloat * points));
TWIGL_DONT_NEED (void, glMap2d, (GLenum target, GLdouble u1, GLdouble u2, GLint ustride, GLint uorder, GLdouble v1, GLdouble v2, GLint vstride, GLint vorder, const GLdouble * points));
TWIGL_DONT_NEED (void, glMap2f, (GLenum target, GLfloat u1, GLfloat u2, GLint ustride, GLint uorder, GLfloat v1, GLfloat v2, GLint vstride, GLint vorder, const GLfloat * points));
TWIGL_DONT_NEED (void, glMapGrid1d, (GLint un, GLdouble u1, GLdouble u2));
TWIGL_DONT_NEED (void, glMapGrid1f, (GLint un, GLfloat u1, GLfloat u2));
TWIGL_DONT_NEED (void, glMapGrid2d, (GLint un, GLdouble u1, GLdouble u2, GLint vn, GLdouble v1, GLdouble v2));
TWIGL_DONT_NEED (void, glMapGrid2f, (GLint un, GLfloat u1, GLfloat u2, GLint vn, GLfloat v1, GLfloat v2));
TWIGL_DONT_NEED (void, glMaterialf, (GLenum face, GLenum pname, GLfloat param));
TWIGL_DONT_NEED (void, glMaterialfv, (GLenum face, GLenum pname, const GLfloat * params));
TWIGL_DONT_NEED (void, glMateriali, (GLenum face, GLenum pname, GLint param));
TWIGL_DONT_NEED (void, glMaterialiv, (GLenum face, GLenum pname, const GLint * params));
TWIGL_NEED (void, glMatrixMode, (GLenum mode));
TWIGL_DONT_NEED (void, glMinmax, (GLenum, GLenum, GLboolean));
TWIGL_EXT_DONT_WANT (void, glMinmaxEXT, (GLenum, GLenum, GLboolean));
TWIGL_DONT_NEED (void, glMultMatrixd, (const GLdouble * m));
TWIGL_DONT_NEED (void, glMultMatrixf, (const GLfloat * m));
TWIGL_EXT_DONT_WANT (void, glMultTransposeMatrixdARB, (const GLdouble *));
TWIGL_EXT_DONT_WANT (void, glMultTransposeMatrixfARB, (const GLfloat *));
TWIGL_EXT_DONT_WANT (void, glMultiDrawArraysEXT, (GLenum, GLint *, GLsizei *, GLsizei));
TWIGL_EXT_DONT_WANT (void, glMultiDrawElementsEXT, (GLenum, const GLsizei *, GLenum, const GLvoid * *, GLsizei));
TWIGL_EXT_DONT_WANT (void, glMultiModeDrawArraysIBM, (GLenum, const GLint *, const GLsizei *, GLsizei, GLint));
TWIGL_EXT_DONT_WANT (void, glMultiModeDrawElementsIBM, (const GLenum *, const GLsizei *, GLenum, const GLvoid * *, GLsizei, GLint));
TWIGL_EXT_DONT_WANT (void, glMultiTexCoord1dARB, (GLenum, GLdouble));
TWIGL_EXT_DONT_WANT (void, glMultiTexCoord1dvARB, (GLenum, const GLdouble *));
TWIGL_EXT_DONT_WANT (void, glMultiTexCoord1fARB, (GLenum, GLfloat));
TWIGL_EXT_DONT_WANT (void, glMultiTexCoord1fvARB, (GLenum, const GLfloat *));
TWIGL_EXT_DONT_WANT (void, glMultiTexCoord1iARB, (GLenum, GLint));
TWIGL_EXT_DONT_WANT (void, glMultiTexCoord1ivARB, (GLenum, const GLint *));
TWIGL_EXT_DONT_WANT (void, glMultiTexCoord1sARB, (GLenum, GLshort));
TWIGL_EXT_DONT_WANT (void, glMultiTexCoord1svARB, (GLenum, const GLshort *));
TWIGL_EXT_DONT_WANT (void, glMultiTexCoord2dARB, (GLenum, GLdouble, GLdouble));
TWIGL_EXT_DONT_WANT (void, glMultiTexCoord2dvARB, (GLenum, const GLdouble *));
TWIGL_EXT_WANT (void, glMultiTexCoord2fARB, (GLenum, GLfloat, GLfloat));
TWIGL_EXT_DONT_WANT (void, glMultiTexCoord2fvARB, (GLenum, const GLfloat *));
TWIGL_EXT_DONT_WANT (void, glMultiTexCoord2iARB, (GLenum, GLint, GLint));
TWIGL_EXT_DONT_WANT (void, glMultiTexCoord2ivARB, (GLenum, const GLint *));
TWIGL_EXT_DONT_WANT (void, glMultiTexCoord2sARB, (GLenum, GLshort, GLshort));
TWIGL_EXT_DONT_WANT (void, glMultiTexCoord2svARB, (GLenum, const GLshort *));
TWIGL_EXT_DONT_WANT (void, glMultiTexCoord3dARB, (GLenum, GLdouble, GLdouble, GLdouble));
TWIGL_EXT_DONT_WANT (void, glMultiTexCoord3dvARB, (GLenum, const GLdouble *));
TWIGL_EXT_DONT_WANT (void, glMultiTexCoord3fARB, (GLenum, GLfloat, GLfloat, GLfloat));
TWIGL_EXT_DONT_WANT (void, glMultiTexCoord3fvARB, (GLenum, const GLfloat *));
TWIGL_EXT_DONT_WANT (void, glMultiTexCoord3iARB, (GLenum, GLint, GLint, GLint));
TWIGL_EXT_DONT_WANT (void, glMultiTexCoord3ivARB, (GLenum, const GLint *));
TWIGL_EXT_DONT_WANT (void, glMultiTexCoord3sARB, (GLenum, GLshort, GLshort, GLshort));
TWIGL_EXT_DONT_WANT (void, glMultiTexCoord3svARB, (GLenum, const GLshort *));
TWIGL_EXT_DONT_WANT (void, glMultiTexCoord4dARB, (GLenum, GLdouble, GLdouble, GLdouble, GLdouble));
TWIGL_EXT_DONT_WANT (void, glMultiTexCoord4dvARB, (GLenum, const GLdouble *));
TWIGL_EXT_DONT_WANT (void, glMultiTexCoord4fARB, (GLenum, GLfloat, GLfloat, GLfloat, GLfloat));
TWIGL_EXT_DONT_WANT (void, glMultiTexCoord4fvARB, (GLenum, const GLfloat *));
TWIGL_EXT_DONT_WANT (void, glMultiTexCoord4iARB, (GLenum, GLint, GLint, GLint, GLint));
TWIGL_EXT_DONT_WANT (void, glMultiTexCoord4ivARB, (GLenum, const GLint *));
TWIGL_EXT_DONT_WANT (void, glMultiTexCoord4sARB, (GLenum, GLshort, GLshort, GLshort, GLshort));
TWIGL_EXT_DONT_WANT (void, glMultiTexCoord4svARB, (GLenum, const GLshort *));
TWIGL_DONT_NEED (void, glNewList, (GLuint list, GLenum mode));
TWIGL_EXT_DONT_WANT (void, glNewTraceMESA, (GLbitfield mask, const GLubyte * traceName));
TWIGL_DONT_NEED (void, glNormal3b, (GLbyte nx, GLbyte ny, GLbyte nz));
TWIGL_DONT_NEED (void, glNormal3bv, (const GLbyte * v));
TWIGL_DONT_NEED (void, glNormal3d, (GLdouble nx, GLdouble ny, GLdouble nz));
TWIGL_DONT_NEED (void, glNormal3dv, (const GLdouble * v));
TWIGL_DONT_NEED (void, glNormal3f, (GLfloat nx, GLfloat ny, GLfloat nz));
TWIGL_EXT_DONT_WANT (void, glNormal3fVertex3fSUN, (GLfloat, GLfloat, GLfloat, GLfloat, GLfloat, GLfloat));
TWIGL_EXT_DONT_WANT (void, glNormal3fVertex3fvSUN, (const GLfloat *, const GLfloat *));
TWIGL_DONT_NEED (void, glNormal3fv, (const GLfloat * v));
TWIGL_DONT_NEED (void, glNormal3i, (GLint nx, GLint ny, GLint nz));
TWIGL_DONT_NEED (void, glNormal3iv, (const GLint * v));
TWIGL_DONT_NEED (void, glNormal3s, (GLshort nx, GLshort ny, GLshort nz));
TWIGL_DONT_NEED (void, glNormal3sv, (const GLshort * v));
TWIGL_DONT_NEED (void, glNormalPointer, (GLenum type, GLsizei stride, const GLvoid * ptr));
TWIGL_EXT_DONT_WANT (void, glNormalPointerEXT, (GLenum, GLsizei, GLsizei, const GLvoid *));
TWIGL_EXT_DONT_WANT (void, glNormalPointerListIBM, (GLenum, GLint, const GLvoid * *, GLint));
TWIGL_EXT_DONT_WANT (void, glNormalPointervINTEL, (GLenum, const GLvoid * *));
TWIGL_NEED (void, glOrtho, (GLdouble left, GLdouble right, GLdouble bottom, GLdouble top, GLdouble near_val, GLdouble far_val));
TWIGL_DONT_NEED (void, glPassThrough, (GLfloat token));
TWIGL_DONT_NEED (void, glPixelMapfv, (GLenum map, GLint mapsize, const GLfloat * values));
TWIGL_DONT_NEED (void, glPixelMapuiv, (GLenum map, GLint mapsize, const GLuint * values));
TWIGL_DONT_NEED (void, glPixelMapusv, (GLenum map, GLint mapsize, const GLushort * values));
TWIGL_DONT_NEED (void, glPixelStoref, (GLenum pname, GLfloat param));
TWIGL_NEED (void, glPixelStorei, (GLenum pname, GLint param));
TWIGL_EXT_DONT_WANT (void, glPixelTexGenParameterfSGIS, (GLenum, GLfloat));
TWIGL_EXT_DONT_WANT (void, glPixelTexGenParameterfvSGIS, (GLenum, const GLfloat *));
TWIGL_EXT_DONT_WANT (void, glPixelTexGenParameteriSGIS, (GLenum, GLint));
TWIGL_EXT_DONT_WANT (void, glPixelTexGenParameterivSGIS, (GLenum, const GLint *));
TWIGL_EXT_DONT_WANT (void, glPixelTexGenSGIX, (GLenum));
TWIGL_DONT_NEED (void, glPixelTransferf, (GLenum pname, GLfloat param));
TWIGL_DONT_NEED (void, glPixelTransferi, (GLenum pname, GLint param));
TWIGL_EXT_DONT_WANT (void, glPixelTransformParameterfEXT, (GLenum, GLenum, GLfloat));
TWIGL_EXT_DONT_WANT (void, glPixelTransformParameterfvEXT, (GLenum, GLenum, const GLfloat *));
TWIGL_EXT_DONT_WANT (void, glPixelTransformParameteriEXT, (GLenum, GLenum, GLint));
TWIGL_EXT_DONT_WANT (void, glPixelTransformParameterivEXT, (GLenum, GLenum, const GLint *));
TWIGL_DONT_NEED (void, glPixelZoom, (GLfloat xfactor, GLfloat yfactor));
TWIGL_EXT_DONT_WANT (void, glPointParameterfEXT, (GLenum, GLfloat));
TWIGL_EXT_DONT_WANT (void, glPointParameterfSGIS, (GLenum, GLfloat));
TWIGL_EXT_DONT_WANT (void, glPointParameterfvEXT, (GLenum, const GLfloat *));
TWIGL_EXT_DONT_WANT (void, glPointParameterfvSGIS, (GLenum, const GLfloat *));
TWIGL_DONT_NEED (void, glPointSize, (GLfloat size));
TWIGL_EXT_DONT_WANT (GLint, glPollAsyncSGIX, (GLuint *));
TWIGL_EXT_DONT_WANT (GLint, glPollInstrumentsSGIX, (GLint *));
TWIGL_NEED (void, glPolygonMode, (GLenum face, GLenum mode));
TWIGL_DONT_NEED (void, glPolygonOffset, (GLfloat factor, GLfloat units));
TWIGL_EXT_DONT_WANT (void, glPolygonOffsetEXT, (GLfloat, GLfloat));
TWIGL_DONT_NEED (void, glPolygonStipple, (const GLubyte * mask));
TWIGL_DONT_NEED (void, glPopAttrib, (void));
TWIGL_DONT_NEED (void, glPopClientAttrib, (void));
TWIGL_NEED (void, glPopMatrix, (void));
TWIGL_DONT_NEED (void, glPopName, (void));
TWIGL_DONT_NEED (void, glPrioritizeTextures, (GLsizei n, const GLuint * textures, const GLclampf * priorities));
TWIGL_EXT_DONT_WANT (void, glPrioritizeTexturesEXT, (GLsizei, const GLuint *, const GLclampf *));
TWIGL_DONT_NEED (void, glPushAttrib, (GLbitfield mask));
TWIGL_DONT_NEED (void, glPushClientAttrib, (GLbitfield mask));
TWIGL_NEED (void, glPushMatrix, (void));
TWIGL_DONT_NEED (void, glPushName, (GLuint name));
TWIGL_DONT_NEED (void, glRasterPos2d, (GLdouble x, GLdouble y));
TWIGL_DONT_NEED (void, glRasterPos2dv, (const GLdouble * v));
TWIGL_DONT_NEED (void, glRasterPos2f, (GLfloat x, GLfloat y));
TWIGL_DONT_NEED (void, glRasterPos2fv, (const GLfloat * v));
TWIGL_DONT_NEED (void, glRasterPos2i, (GLint x, GLint y));
TWIGL_DONT_NEED (void, glRasterPos2iv, (const GLint * v));
TWIGL_DONT_NEED (void, glRasterPos2s, (GLshort x, GLshort y));
TWIGL_DONT_NEED (void, glRasterPos2sv, (const GLshort * v));
TWIGL_DONT_NEED (void, glRasterPos3d, (GLdouble x, GLdouble y, GLdouble z));
TWIGL_DONT_NEED (void, glRasterPos3dv, (const GLdouble * v));
TWIGL_DONT_NEED (void, glRasterPos3f, (GLfloat x, GLfloat y, GLfloat z));
TWIGL_DONT_NEED (void, glRasterPos3fv, (const GLfloat * v));
TWIGL_DONT_NEED (void, glRasterPos3i, (GLint x, GLint y, GLint z));
TWIGL_DONT_NEED (void, glRasterPos3iv, (const GLint * v));
TWIGL_DONT_NEED (void, glRasterPos3s, (GLshort x, GLshort y, GLshort z));
TWIGL_DONT_NEED (void, glRasterPos3sv, (const GLshort * v));
TWIGL_DONT_NEED (void, glRasterPos4d, (GLdouble x, GLdouble y, GLdouble z, GLdouble w));
TWIGL_DONT_NEED (void, glRasterPos4dv, (const GLdouble * v));
TWIGL_DONT_NEED (void, glRasterPos4f, (GLfloat x, GLfloat y, GLfloat z, GLfloat w));
TWIGL_DONT_NEED (void, glRasterPos4fv, (const GLfloat * v));
TWIGL_DONT_NEED (void, glRasterPos4i, (GLint x, GLint y, GLint z, GLint w));
TWIGL_DONT_NEED (void, glRasterPos4iv, (const GLint * v));
TWIGL_DONT_NEED (void, glRasterPos4s, (GLshort x, GLshort y, GLshort z, GLshort w));
TWIGL_DONT_NEED (void, glRasterPos4sv, (const GLshort * v));
TWIGL_DONT_NEED (void, glReadBuffer, (GLenum mode));
TWIGL_EXT_DONT_WANT (void, glReadInstrumentsSGIX, (GLint));
TWIGL_NEED (void, glReadPixels, (GLint x, GLint y, GLsizei width, GLsizei height, GLenum format, GLenum type, GLvoid * pixels));
TWIGL_DONT_NEED (void, glRectd, (GLdouble x1, GLdouble y1, GLdouble x2, GLdouble y2));
TWIGL_DONT_NEED (void, glRectdv, (const GLdouble * v1, const GLdouble * v2));
TWIGL_DONT_NEED (void, glRectf, (GLfloat x1, GLfloat y1, GLfloat x2, GLfloat y2));
TWIGL_DONT_NEED (void, glRectfv, (const GLfloat * v1, const GLfloat * v2));
TWIGL_DONT_NEED (void, glRecti, (GLint x1, GLint y1, GLint x2, GLint y2));
TWIGL_DONT_NEED (void, glRectiv, (const GLint * v1, const GLint * v2));
TWIGL_DONT_NEED (void, glRects, (GLshort x1, GLshort y1, GLshort x2, GLshort y2));
TWIGL_DONT_NEED (void, glRectsv, (const GLshort * v1, const GLshort * v2));
TWIGL_EXT_DONT_WANT (void, glReferencePlaneSGIX, (const GLdouble *));
TWIGL_DONT_NEED (GLint, glRenderMode, (GLenum mode));
TWIGL_EXT_DONT_WANT (void, glReplacementCodePointerSUN, (GLenum, GLsizei, const GLvoid * *));
TWIGL_EXT_DONT_WANT (void, glReplacementCodeubSUN, (GLubyte));
TWIGL_EXT_DONT_WANT (void, glReplacementCodeubvSUN, (const GLubyte *));
TWIGL_EXT_DONT_WANT (void, glReplacementCodeuiColor3fVertex3fSUN, (GLenum, GLfloat, GLfloat, GLfloat, GLfloat, GLfloat, GLfloat));
TWIGL_EXT_DONT_WANT (void, glReplacementCodeuiColor3fVertex3fvSUN, (const GLenum *, const GLfloat *, const GLfloat *));
TWIGL_EXT_DONT_WANT (void, glReplacementCodeuiColor4fNormal3fVertex3fSUN, (GLenum, GLfloat, GLfloat, GLfloat, GLfloat, GLfloat, GLfloat, GLfloat, GLfloat, GLfloat, GLfloat));
TWIGL_EXT_DONT_WANT (void, glReplacementCodeuiColor4fNormal3fVertex3fvSUN, (const GLenum *, const GLfloat *, const GLfloat *, const GLfloat *));
TWIGL_EXT_DONT_WANT (void, glReplacementCodeuiColor4ubVertex3fSUN, (GLenum, GLubyte, GLubyte, GLubyte, GLubyte, GLfloat, GLfloat, GLfloat));
TWIGL_EXT_DONT_WANT (void, glReplacementCodeuiColor4ubVertex3fvSUN, (const GLenum *, const GLubyte *, const GLfloat *));
TWIGL_EXT_DONT_WANT (void, glReplacementCodeuiNormal3fVertex3fSUN, (GLenum, GLfloat, GLfloat, GLfloat, GLfloat, GLfloat, GLfloat));
TWIGL_EXT_DONT_WANT (void, glReplacementCodeuiNormal3fVertex3fvSUN, (const GLenum *, const GLfloat *, const GLfloat *));
TWIGL_EXT_DONT_WANT (void, glReplacementCodeuiSUN, (GLuint));
TWIGL_EXT_DONT_WANT (void, glReplacementCodeuiTexCoord2fColor4fNormal3fVertex3fSUN, (GLenum, GLfloat, GLfloat, GLfloat, GLfloat, GLfloat, GLfloat, GLfloat, GLfloat, GLfloat, GLfloat, GLfloat, GLfloat));
TWIGL_EXT_DONT_WANT (void, glReplacementCodeuiTexCoord2fColor4fNormal3fVertex3fvSUN, (const GLenum *, const GLfloat *, const GLfloat *, const GLfloat *, const GLfloat *));
TWIGL_EXT_DONT_WANT (void, glReplacementCodeuiTexCoord2fNormal3fVertex3fSUN, (GLenum, GLfloat, GLfloat, GLfloat, GLfloat, GLfloat, GLfloat, GLfloat, GLfloat));
TWIGL_EXT_DONT_WANT (void, glReplacementCodeuiTexCoord2fNormal3fVertex3fvSUN, (const GLenum *, const GLfloat *, const GLfloat *, const GLfloat *));
TWIGL_EXT_DONT_WANT (void, glReplacementCodeuiTexCoord2fVertex3fSUN, (GLenum, GLfloat, GLfloat, GLfloat, GLfloat, GLfloat));
TWIGL_EXT_DONT_WANT (void, glReplacementCodeuiTexCoord2fVertex3fvSUN, (const GLenum *, const GLfloat *, const GLfloat *));
TWIGL_EXT_DONT_WANT (void, glReplacementCodeuiVertex3fSUN, (GLenum, GLfloat, GLfloat, GLfloat));
TWIGL_EXT_DONT_WANT (void, glReplacementCodeuiVertex3fvSUN, (const GLenum *, const GLfloat *));
TWIGL_EXT_DONT_WANT (void, glReplacementCodeuivSUN, (const GLuint *));
TWIGL_EXT_DONT_WANT (void, glReplacementCodeusSUN, (GLushort));
TWIGL_EXT_DONT_WANT (void, glReplacementCodeusvSUN, (const GLushort *));
TWIGL_DONT_NEED (void, glResetHistogram, (GLenum));
TWIGL_EXT_DONT_WANT (void, glResetHistogramEXT, (GLenum));
TWIGL_DONT_NEED (void, glResetMinmax, (GLenum));
TWIGL_EXT_DONT_WANT (void, glResetMinmaxEXT, (GLenum));
TWIGL_EXT_DONT_WANT (void, glResizeBuffersMESA, (void));
TWIGL_DONT_NEED (void, glRotated, (GLdouble angle, GLdouble x, GLdouble y, GLdouble z));
TWIGL_NEED (void, glRotatef, (GLfloat angle, GLfloat x, GLfloat y, GLfloat z));
TWIGL_EXT_DONT_WANT (void, glSampleCoverageARB, (GLclampf, GLboolean));
TWIGL_EXT_DONT_WANT (void, glSampleMaskEXT, (GLclampf, GLboolean));
TWIGL_EXT_DONT_WANT (void, glSampleMaskSGIS, (GLclampf, GLboolean));
TWIGL_EXT_DONT_WANT (void, glSamplePassARB, (GLenum));
TWIGL_EXT_DONT_WANT (void, glSamplePatternEXT, (GLenum));
TWIGL_EXT_DONT_WANT (void, glSamplePatternSGIS, (GLenum));
TWIGL_DONT_NEED (void, glScaled, (GLdouble x, GLdouble y, GLdouble z));
TWIGL_NEED (void, glScalef, (GLfloat x, GLfloat y, GLfloat z));
TWIGL_DONT_NEED (void, glScissor, (GLint x, GLint y, GLsizei width, GLsizei height));
TWIGL_EXT_DONT_WANT (void, glSecondaryColor3bEXT, (GLbyte, GLbyte, GLbyte));
TWIGL_EXT_DONT_WANT (void, glSecondaryColor3bvEXT, (const GLbyte *));
TWIGL_EXT_DONT_WANT (void, glSecondaryColor3dEXT, (GLdouble, GLdouble, GLdouble));
TWIGL_EXT_DONT_WANT (void, glSecondaryColor3dvEXT, (const GLdouble *));
TWIGL_EXT_DONT_WANT (void, glSecondaryColor3fEXT, (GLfloat, GLfloat, GLfloat));
TWIGL_EXT_DONT_WANT (void, glSecondaryColor3fvEXT, (const GLfloat *));
TWIGL_EXT_DONT_WANT (void, glSecondaryColor3iEXT, (GLint, GLint, GLint));
TWIGL_EXT_DONT_WANT (void, glSecondaryColor3ivEXT, (const GLint *));
TWIGL_EXT_DONT_WANT (void, glSecondaryColor3sEXT, (GLshort, GLshort, GLshort));
TWIGL_EXT_DONT_WANT (void, glSecondaryColor3svEXT, (const GLshort *));
TWIGL_EXT_DONT_WANT (void, glSecondaryColor3ubEXT, (GLubyte, GLubyte, GLubyte));
TWIGL_EXT_DONT_WANT (void, glSecondaryColor3ubvEXT, (const GLubyte *));
TWIGL_EXT_DONT_WANT (void, glSecondaryColor3uiEXT, (GLuint, GLuint, GLuint));
TWIGL_EXT_DONT_WANT (void, glSecondaryColor3uivEXT, (const GLuint *));
TWIGL_EXT_DONT_WANT (void, glSecondaryColor3usEXT, (GLushort, GLushort, GLushort));
TWIGL_EXT_DONT_WANT (void, glSecondaryColor3usvEXT, (const GLushort *));
TWIGL_EXT_DONT_WANT (void, glSecondaryColorPointerEXT, (GLint, GLenum, GLsizei, GLvoid *));
TWIGL_EXT_DONT_WANT (void, glSecondaryColorPointerListIBM, (GLint, GLenum, GLint, const GLvoid * *, GLint));
TWIGL_DONT_NEED (void, glSelectBuffer, (GLsizei size, GLuint * buffer));
TWIGL_DONT_NEED (void, glSeparableFilter2D, (GLenum, GLenum, GLsizei, GLsizei, GLenum, GLenum, const GLvoid *, const GLvoid *));
TWIGL_EXT_DONT_WANT (void, glSeparableFilter2DEXT, (GLenum, GLenum, GLsizei, GLsizei, GLenum, GLenum, const GLvoid *, const GLvoid *));
TWIGL_DONT_NEED (void, glShadeModel, (GLenum mode));
TWIGL_EXT_DONT_WANT (void, glSharpenTexFuncSGIS, (GLenum, GLsizei, const GLfloat *));
TWIGL_EXT_DONT_WANT (void, glSpriteParameterfSGIX, (GLenum, GLfloat));
TWIGL_EXT_DONT_WANT (void, glSpriteParameterfvSGIX, (GLenum, const GLfloat *));
TWIGL_EXT_DONT_WANT (void, glSpriteParameteriSGIX, (GLenum, GLint));
TWIGL_EXT_DONT_WANT (void, glSpriteParameterivSGIX, (GLenum, const GLint *));
TWIGL_EXT_DONT_WANT (void, glStartInstrumentsSGIX, (void));
TWIGL_DONT_NEED (void, glStencilFunc, (GLenum func, GLint ref, GLuint mask));
TWIGL_DONT_NEED (void, glStencilMask, (GLuint mask));
TWIGL_DONT_NEED (void, glStencilOp, (GLenum fail, GLenum zfail, GLenum zpass));
TWIGL_EXT_DONT_WANT (void, glStopInstrumentsSGIX, (GLint));
TWIGL_EXT_DONT_WANT (void, glTagSampleBufferSGIX, (void));
TWIGL_EXT_DONT_WANT (void, glTangent3bEXT, (GLbyte, GLbyte, GLbyte));
TWIGL_EXT_DONT_WANT (void, glTangent3bvEXT, (const GLbyte *));
TWIGL_EXT_DONT_WANT (void, glTangent3dEXT, (GLdouble, GLdouble, GLdouble));
TWIGL_EXT_DONT_WANT (void, glTangent3dvEXT, (const GLdouble *));
TWIGL_EXT_DONT_WANT (void, glTangent3fEXT, (GLfloat, GLfloat, GLfloat));
TWIGL_EXT_DONT_WANT (void, glTangent3fvEXT, (const GLfloat *));
TWIGL_EXT_DONT_WANT (void, glTangent3iEXT, (GLint, GLint, GLint));
TWIGL_EXT_DONT_WANT (void, glTangent3ivEXT, (const GLint *));
TWIGL_EXT_DONT_WANT (void, glTangent3sEXT, (GLshort, GLshort, GLshort));
TWIGL_EXT_DONT_WANT (void, glTangent3svEXT, (const GLshort *));
TWIGL_EXT_DONT_WANT (void, glTangentPointerEXT, (GLenum, GLsizei, const GLvoid *));
TWIGL_EXT_DONT_WANT (void, glTbufferMask3DFX, (GLuint));
TWIGL_DONT_NEED (void, glTexCoord1d, (GLdouble s));
TWIGL_DONT_NEED (void, glTexCoord1dv, (const GLdouble * v));
TWIGL_DONT_NEED (void, glTexCoord1f, (GLfloat s));
TWIGL_DONT_NEED (void, glTexCoord1fv, (const GLfloat * v));
TWIGL_DONT_NEED (void, glTexCoord1i, (GLint s));
TWIGL_DONT_NEED (void, glTexCoord1iv, (const GLint * v));
TWIGL_DONT_NEED (void, glTexCoord1s, (GLshort s));
TWIGL_DONT_NEED (void, glTexCoord1sv, (const GLshort * v));
TWIGL_DONT_NEED (void, glTexCoord2d, (GLdouble s, GLdouble t));
TWIGL_DONT_NEED (void, glTexCoord2dv, (const GLdouble * v));
TWIGL_NEED (void, glTexCoord2f, (GLfloat s, GLfloat t));
TWIGL_EXT_DONT_WANT (void, glTexCoord2fColor3fVertex3fSUN, (GLfloat, GLfloat, GLfloat, GLfloat, GLfloat, GLfloat, GLfloat, GLfloat));
TWIGL_EXT_DONT_WANT (void, glTexCoord2fColor3fVertex3fvSUN, (const GLfloat *, const GLfloat *, const GLfloat *));
TWIGL_EXT_DONT_WANT (void, glTexCoord2fColor4fNormal3fVertex3fSUN, (GLfloat, GLfloat, GLfloat, GLfloat, GLfloat, GLfloat, GLfloat, GLfloat, GLfloat, GLfloat, GLfloat, GLfloat));
TWIGL_EXT_DONT_WANT (void, glTexCoord2fColor4fNormal3fVertex3fvSUN, (const GLfloat *, const GLfloat *, const GLfloat *, const GLfloat *));
TWIGL_EXT_DONT_WANT (void, glTexCoord2fColor4ubVertex3fSUN, (GLfloat, GLfloat, GLubyte, GLubyte, GLubyte, GLubyte, GLfloat, GLfloat, GLfloat));
TWIGL_EXT_DONT_WANT (void, glTexCoord2fColor4ubVertex3fvSUN, (const GLfloat *, const GLubyte *, const GLfloat *));
TWIGL_EXT_DONT_WANT (void, glTexCoord2fNormal3fVertex3fSUN, (GLfloat, GLfloat, GLfloat, GLfloat, GLfloat, GLfloat, GLfloat, GLfloat));
TWIGL_EXT_DONT_WANT (void, glTexCoord2fNormal3fVertex3fvSUN, (const GLfloat *, const GLfloat *, const GLfloat *));
TWIGL_EXT_DONT_WANT (void, glTexCoord2fVertex3fSUN, (GLfloat, GLfloat, GLfloat, GLfloat, GLfloat));
TWIGL_EXT_DONT_WANT (void, glTexCoord2fVertex3fvSUN, (const GLfloat *, const GLfloat *));
TWIGL_NEED (void, glTexCoord2fv, (const GLfloat * v));
TWIGL_DONT_NEED (void, glTexCoord2i, (GLint s, GLint t));
TWIGL_DONT_NEED (void, glTexCoord2iv, (const GLint * v));
TWIGL_DONT_NEED (void, glTexCoord2s, (GLshort s, GLshort t));
TWIGL_DONT_NEED (void, glTexCoord2sv, (const GLshort * v));
TWIGL_DONT_NEED (void, glTexCoord3d, (GLdouble s, GLdouble t, GLdouble r));
TWIGL_DONT_NEED (void, glTexCoord3dv, (const GLdouble * v));
TWIGL_DONT_NEED (void, glTexCoord3f, (GLfloat s, GLfloat t, GLfloat r));
TWIGL_DONT_NEED (void, glTexCoord3fv, (const GLfloat * v));
TWIGL_DONT_NEED (void, glTexCoord3i, (GLint s, GLint t, GLint r));
TWIGL_DONT_NEED (void, glTexCoord3iv, (const GLint * v));
TWIGL_DONT_NEED (void, glTexCoord3s, (GLshort s, GLshort t, GLshort r));
TWIGL_DONT_NEED (void, glTexCoord3sv, (const GLshort * v));
TWIGL_DONT_NEED (void, glTexCoord4d, (GLdouble s, GLdouble t, GLdouble r, GLdouble q));
TWIGL_DONT_NEED (void, glTexCoord4dv, (const GLdouble * v));
TWIGL_DONT_NEED (void, glTexCoord4f, (GLfloat s, GLfloat t, GLfloat r, GLfloat q));
TWIGL_EXT_DONT_WANT (void, glTexCoord4fColor4fNormal3fVertex4fSUN, (GLfloat, GLfloat, GLfloat, GLfloat, GLfloat, GLfloat, GLfloat, GLfloat, GLfloat, GLfloat, GLfloat, GLfloat, GLfloat, GLfloat, GLfloat));
TWIGL_EXT_DONT_WANT (void, glTexCoord4fColor4fNormal3fVertex4fvSUN, (const GLfloat *, const GLfloat *, const GLfloat *, const GLfloat *));
TWIGL_EXT_DONT_WANT (void, glTexCoord4fVertex4fSUN, (GLfloat, GLfloat, GLfloat, GLfloat, GLfloat, GLfloat, GLfloat, GLfloat));
TWIGL_EXT_DONT_WANT (void, glTexCoord4fVertex4fvSUN, (const GLfloat *, const GLfloat *));
TWIGL_DONT_NEED (void, glTexCoord4fv, (const GLfloat * v));
TWIGL_DONT_NEED (void, glTexCoord4i, (GLint s, GLint t, GLint r, GLint q));
TWIGL_DONT_NEED (void, glTexCoord4iv, (const GLint * v));
TWIGL_DONT_NEED (void, glTexCoord4s, (GLshort s, GLshort t, GLshort r, GLshort q));
TWIGL_DONT_NEED (void, glTexCoord4sv, (const GLshort * v));
TWIGL_DONT_NEED (void, glTexCoordPointer, (GLint size, GLenum type, GLsizei stride, const GLvoid * ptr));
TWIGL_EXT_DONT_WANT (void, glTexCoordPointerEXT, (GLint, GLenum, GLsizei, GLsizei, const GLvoid *));
TWIGL_EXT_DONT_WANT (void, glTexCoordPointerListIBM, (GLint, GLenum, GLint, const GLvoid * *, GLint));
TWIGL_EXT_DONT_WANT (void, glTexCoordPointervINTEL, (GLint, GLenum, const GLvoid * *));
TWIGL_NEED (void, glTexEnvf, (GLenum target, GLenum pname, GLfloat param));
TWIGL_DONT_NEED (void, glTexEnvfv, (GLenum target, GLenum pname, const GLfloat * params));
TWIGL_DONT_NEED (void, glTexEnvi, (GLenum target, GLenum pname, GLint param));
TWIGL_DONT_NEED (void, glTexEnviv, (GLenum target, GLenum pname, const GLint * params));
TWIGL_EXT_DONT_WANT (void, glTexFilterFuncSGIS, (GLenum, GLenum, GLsizei, const GLfloat *));
TWIGL_DONT_NEED (void, glTexGend, (GLenum coord, GLenum pname, GLdouble param));
TWIGL_DONT_NEED (void, glTexGendv, (GLenum coord, GLenum pname, const GLdouble * params));
TWIGL_DONT_NEED (void, glTexGenf, (GLenum coord, GLenum pname, GLfloat param));
TWIGL_DONT_NEED (void, glTexGenfv, (GLenum coord, GLenum pname, const GLfloat * params));
TWIGL_DONT_NEED (void, glTexGeni, (GLenum coord, GLenum pname, GLint param));
TWIGL_DONT_NEED (void, glTexGeniv, (GLenum coord, GLenum pname, const GLint * params));
TWIGL_DONT_NEED (void, glTexImage1D, (GLenum target, GLint level, GLint internalFormat, GLsizei width, GLint border, GLenum format, GLenum type, const GLvoid * pixels));
TWIGL_NEED (void, glTexImage2D, (GLenum target, GLint level, GLint internalFormat, GLsizei width, GLsizei height, GLint border, GLenum format, GLenum type, const GLvoid * pixels));
TWIGL_DONT_NEED (void, glTexImage3D, (GLenum, GLint, GLint, GLsizei, GLsizei, GLsizei, GLint, GLenum, GLenum, const GLvoid *));
TWIGL_EXT_DONT_WANT (void, glTexImage3DEXT, (GLenum, GLint, GLenum, GLsizei, GLsizei, GLsizei, GLint, GLenum, GLenum, const GLvoid *));
TWIGL_EXT_DONT_WANT (void, glTexImage4DSGIS, (GLenum, GLint, GLenum, GLsizei, GLsizei, GLsizei, GLsizei, GLint, GLenum, GLenum, const GLvoid *));
TWIGL_NEED (void, glTexParameterf, (GLenum target, GLenum pname, GLfloat param));
TWIGL_DONT_NEED (void, glTexParameterfv, (GLenum target, GLenum pname, const GLfloat * params));
TWIGL_DONT_NEED (void, glTexParameteri, (GLenum target, GLenum pname, GLint param));
TWIGL_DONT_NEED (void, glTexParameteriv, (GLenum target, GLenum pname, const GLint * params));
TWIGL_DONT_NEED (void, glTexSubImage1D, (GLenum target, GLint level, GLint xoffset, GLsizei width, GLenum format, GLenum type, const GLvoid * pixels));
TWIGL_EXT_DONT_WANT (void, glTexSubImage1DEXT, (GLenum, GLint, GLint, GLsizei, GLenum, GLenum, const GLvoid *));
TWIGL_NEED (void, glTexSubImage2D, (GLenum target, GLint level, GLint xoffset, GLint yoffset, GLsizei width, GLsizei height, GLenum format, GLenum type, const GLvoid * pixels));
TWIGL_EXT_DONT_WANT (void, glTexSubImage2DEXT, (GLenum, GLint, GLint, GLint, GLsizei, GLsizei, GLenum, GLenum, const GLvoid *));
TWIGL_DONT_NEED (void, glTexSubImage3D, (GLenum, GLint, GLint, GLint, GLint, GLsizei, GLsizei, GLsizei, GLenum, GLenum, const GLvoid *));
TWIGL_EXT_DONT_WANT (void, glTexSubImage3DEXT, (GLenum, GLint, GLint, GLint, GLint, GLsizei, GLsizei, GLsizei, GLenum, GLenum, const GLvoid *));
TWIGL_EXT_DONT_WANT (void, glTexSubImage4DSGIS, (GLenum, GLint, GLint, GLint, GLint, GLint, GLsizei, GLsizei, GLsizei, GLsizei, GLenum, GLenum, const GLvoid *));
TWIGL_EXT_DONT_WANT (void, glTextureColorMaskSGIS, (GLboolean, GLboolean, GLboolean, GLboolean));
TWIGL_EXT_DONT_WANT (void, glTextureLightEXT, (GLenum));
TWIGL_EXT_DONT_WANT (void, glTextureMaterialEXT, (GLenum, GLenum));
TWIGL_EXT_DONT_WANT (void, glTextureNormalEXT, (GLenum));
TWIGL_EXT_DONT_WANT (void, glTraceAssertAttribMESA, (GLbitfield attribMask));
TWIGL_EXT_DONT_WANT (void, glTraceCommentMESA, (const GLubyte * comment));
TWIGL_EXT_DONT_WANT (void, glTraceListMESA, (GLuint name, const GLubyte * comment));
TWIGL_EXT_DONT_WANT (void, glTracePointerMESA, (GLvoid * pointer, const GLubyte * comment));
TWIGL_EXT_DONT_WANT (void, glTracePointerRangeMESA, (const GLvoid * first, const GLvoid * last, const GLubyte * comment));
TWIGL_EXT_DONT_WANT (void, glTraceTextureMESA, (GLuint name, const GLubyte * comment));
TWIGL_DONT_NEED (void, glTranslated, (GLdouble x, GLdouble y, GLdouble z));
TWIGL_NEED (void, glTranslatef, (GLfloat x, GLfloat y, GLfloat z));
TWIGL_EXT_DONT_WANT (void, glUnlockArraysEXT, (void));
TWIGL_DONT_NEED (void, glVertex2d, (GLdouble x, GLdouble y));
TWIGL_DONT_NEED (void, glVertex2dv, (const GLdouble * v));
TWIGL_NEED (void, glVertex2f, (GLfloat x, GLfloat y));
TWIGL_DONT_NEED (void, glVertex2fv, (const GLfloat * v));
TWIGL_DONT_NEED (void, glVertex2i, (GLint x, GLint y));
TWIGL_DONT_NEED (void, glVertex2iv, (const GLint * v));
TWIGL_DONT_NEED (void, glVertex2s, (GLshort x, GLshort y));
TWIGL_DONT_NEED (void, glVertex2sv, (const GLshort * v));
TWIGL_DONT_NEED (void, glVertex3d, (GLdouble x, GLdouble y, GLdouble z));
TWIGL_DONT_NEED (void, glVertex3dv, (const GLdouble * v));
TWIGL_NEED (void, glVertex3f, (GLfloat x, GLfloat y, GLfloat z));
TWIGL_NEED (void, glVertex3fv, (const GLfloat * v));
TWIGL_DONT_NEED (void, glVertex3i, (GLint x, GLint y, GLint z));
TWIGL_DONT_NEED (void, glVertex3iv, (const GLint * v));
TWIGL_DONT_NEED (void, glVertex3s, (GLshort x, GLshort y, GLshort z));
TWIGL_DONT_NEED (void, glVertex3sv, (const GLshort * v));
TWIGL_DONT_NEED (void, glVertex4d, (GLdouble x, GLdouble y, GLdouble z, GLdouble w));
TWIGL_DONT_NEED (void, glVertex4dv, (const GLdouble * v));
TWIGL_DONT_NEED (void, glVertex4f, (GLfloat x, GLfloat y, GLfloat z, GLfloat w));
TWIGL_DONT_NEED (void, glVertex4fv, (const GLfloat * v));
TWIGL_DONT_NEED (void, glVertex4i, (GLint x, GLint y, GLint z, GLint w));
TWIGL_DONT_NEED (void, glVertex4iv, (const GLint * v));
TWIGL_DONT_NEED (void, glVertex4s, (GLshort x, GLshort y, GLshort z, GLshort w));
TWIGL_DONT_NEED (void, glVertex4sv, (const GLshort * v));
TWIGL_EXT_DONT_WANT (void, glVertexArrayRangeNV, (GLsizei, const GLvoid *));
TWIGL_DONT_NEED (void, glVertexPointer, (GLint size, GLenum type, GLsizei stride, const GLvoid * ptr));
TWIGL_EXT_DONT_WANT (void, glVertexPointerEXT, (GLint, GLenum, GLsizei, GLsizei, const GLvoid *));
TWIGL_EXT_DONT_WANT (void, glVertexPointerListIBM, (GLint, GLenum, GLint, const GLvoid * *, GLint));
TWIGL_EXT_DONT_WANT (void, glVertexPointervINTEL, (GLint, GLenum, const GLvoid * *));
TWIGL_EXT_DONT_WANT (void, glVertexWeightPointerEXT, (GLsizei, GLenum, GLsizei, const GLvoid *));
TWIGL_EXT_DONT_WANT (void, glVertexWeightfEXT, (GLfloat));
TWIGL_EXT_DONT_WANT (void, glVertexWeightfvEXT, (const GLfloat *));
TWIGL_NEED (void, glViewport, (GLint x, GLint y, GLsizei width, GLsizei height));
TWIGL_EXT_DONT_WANT (void, glWindowPos2dMESA, (GLdouble, GLdouble));
TWIGL_EXT_DONT_WANT (void, glWindowPos2dvMESA, (const GLdouble *));
TWIGL_EXT_DONT_WANT (void, glWindowPos2fMESA, (GLfloat, GLfloat));
TWIGL_EXT_DONT_WANT (void, glWindowPos2fvMESA, (const GLfloat *));
TWIGL_EXT_DONT_WANT (void, glWindowPos2iMESA, (GLint, GLint));
TWIGL_EXT_DONT_WANT (void, glWindowPos2ivMESA, (const GLint *));
TWIGL_EXT_DONT_WANT (void, glWindowPos2sMESA, (GLshort, GLshort));
TWIGL_EXT_DONT_WANT (void, glWindowPos2svMESA, (const GLshort *));
TWIGL_EXT_DONT_WANT (void, glWindowPos3dMESA, (GLdouble, GLdouble, GLdouble));
TWIGL_EXT_DONT_WANT (void, glWindowPos3dvMESA, (const GLdouble *));
TWIGL_EXT_DONT_WANT (void, glWindowPos3fMESA, (GLfloat, GLfloat, GLfloat));
TWIGL_EXT_DONT_WANT (void, glWindowPos3fvMESA, (const GLfloat *));
TWIGL_EXT_DONT_WANT (void, glWindowPos3iMESA, (GLint, GLint, GLint));
TWIGL_EXT_DONT_WANT (void, glWindowPos3ivMESA, (const GLint *));
TWIGL_EXT_DONT_WANT (void, glWindowPos3sMESA, (GLshort, GLshort, GLshort));
TWIGL_EXT_DONT_WANT (void, glWindowPos3svMESA, (const GLshort *));
TWIGL_EXT_DONT_WANT (void, glWindowPos4dMESA, (GLdouble, GLdouble, GLdouble, GLdouble));
TWIGL_EXT_DONT_WANT (void, glWindowPos4dvMESA, (const GLdouble *));
TWIGL_EXT_DONT_WANT (void, glWindowPos4fMESA, (GLfloat, GLfloat, GLfloat, GLfloat));
TWIGL_EXT_DONT_WANT (void, glWindowPos4fvMESA, (const GLfloat *));
TWIGL_EXT_DONT_WANT (void, glWindowPos4iMESA, (GLint, GLint, GLint, GLint));
TWIGL_EXT_DONT_WANT (void, glWindowPos4ivMESA, (const GLint *));
TWIGL_EXT_DONT_WANT (void, glWindowPos4sMESA, (GLshort, GLshort, GLshort, GLshort));
TWIGL_EXT_DONT_WANT (void, glWindowPos4svMESA, (const GLshort *));

#ifdef UNDEF_TWIGL_EXT_DONT_WANT
#undef TWIGL_EXT_DONT_WANT
#endif

#ifdef UNDEF_TWIGL_EXT_WANT
#undef TWIGL_EXT_WANT
#endif

#ifdef UNDEF_TWIGL_DONT_NEED
#undef TWIGL_DONT_NEED
#endif

#ifdef UNDEF_TWIGL_NEED
#undef TWIGL_NEED
#endif
