/*
    gl_defines.h

    GL functions.

    Copyright (C) 1999-2000	Brian Paul.
    Copyright (C) 2001		Zephaniah E. Hull.

    Please refer to doc/copyright/GPL and doc/copyright/mesa for terms
    of license.

    $Id$
*/

#ifndef TWIGL_DONT_NEED
#define TWIGL_DONT_NEED(ret, func, params)
#define UNDEF_TWIGL_DONT_NEED
#endif

TWIGL_DONT_NEED (void, glAccum, (GLenum op, GLfloat value));
TWIGL_DONT_NEED (void, glActiveTextureARB, (GLenum texture));
TWIGL_NEED (void, glAlphaFunc, (GLenum func, GLclampf ref));
TWIGL_DONT_NEED (GLboolean, glAreTexturesResident, (GLsizei n, const GLuint * textures, GLboolean * residences));
TWIGL_DONT_NEED (GLboolean, glAreTexturesResidentEXT, (GLsizei n, const GLuint * textures, GLboolean * residences));
TWIGL_DONT_NEED (void, glArrayElement, (GLint i));
TWIGL_DONT_NEED (void, glArrayElementEXT, (GLint i));
TWIGL_NEED (void, glBegin, (GLenum mode));
TWIGL_NEED (void, glBindTexture, (GLenum target, GLuint texture));
TWIGL_DONT_NEED (void, glBindTextureEXT, (GLenum target, GLuint texture));
TWIGL_DONT_NEED (void, glBitmap, (GLsizei width, GLsizei height, GLfloat xorig, GLfloat yorig, GLfloat xmove, GLfloat ymove, const GLubyte * bitmap));
TWIGL_DONT_NEED (void, glBlendColor, (GLclampf red, GLclampf green, GLclampf blue, GLclampf alpha));
TWIGL_DONT_NEED (void, glBlendColorEXT, (GLclampf red, GLclampf green, GLclampf blue, GLclampf alpha));
TWIGL_DONT_NEED (void, glBlendEquation, (GLenum mode));
TWIGL_DONT_NEED (void, glBlendEquationEXT, (GLenum mode));
TWIGL_NEED (void, glBlendFunc, (GLenum sfactor, GLenum dfactor));
TWIGL_DONT_NEED (void, glCallList, (GLuint list));
TWIGL_DONT_NEED (void, glCallLists, (GLsizei n, GLenum type, const GLvoid * lists));
TWIGL_NEED (void, glClear, (GLbitfield mask));
TWIGL_DONT_NEED (void, glClearAccum, (GLfloat red, GLfloat green, GLfloat blue, GLfloat alpha));
TWIGL_NEED (void, glClearColor, (GLclampf red, GLclampf green, GLclampf blue, GLclampf alpha));
TWIGL_DONT_NEED (void, glClearDepth, (GLclampd depth));
TWIGL_DONT_NEED (void, glClearIndex, (GLfloat c));
TWIGL_DONT_NEED (void, glClearStencil, (GLint s));
TWIGL_DONT_NEED (void, glClientActiveTextureARB, (GLenum texture));
TWIGL_DONT_NEED (void, glClipPlane, (GLenum plane, const GLdouble * equation));
TWIGL_DONT_NEED (void, glColor3b, (GLbyte red, GLbyte green, GLbyte blue));
TWIGL_DONT_NEED (void, glColor3bv, (const GLbyte * v));
TWIGL_DONT_NEED (void, glColor3d, (GLdouble red, GLdouble green, GLdouble blue));
TWIGL_DONT_NEED (void, glColor3dv, (const GLdouble * v));
TWIGL_NEED (void, glColor3f, (GLfloat red, GLfloat green, GLfloat blue));
TWIGL_NEED (void, glColor3fv, (const GLfloat * v));
TWIGL_DONT_NEED (void, glColor3i, (GLint red, GLint green, GLint blue));
TWIGL_DONT_NEED (void, glColor3iv, (const GLint * v));
TWIGL_DONT_NEED (void, glColor3s, (GLshort red, GLshort green, GLshort blue));
TWIGL_DONT_NEED (void, glColor3sv, (const GLshort * v));
TWIGL_DONT_NEED (void, glColor3ub, (GLubyte red, GLubyte green, GLubyte blue));
TWIGL_NEED (void, glColor3ubv, (const GLubyte * v));
TWIGL_DONT_NEED (void, glColor3ui, (GLuint red, GLuint green, GLuint blue));
TWIGL_DONT_NEED (void, glColor3uiv, (const GLuint * v));
TWIGL_DONT_NEED (void, glColor3us, (GLushort red, GLushort green, GLushort blue));
TWIGL_DONT_NEED (void, glColor3usv, (const GLushort * v));
TWIGL_DONT_NEED (void, glColor4b, (GLbyte red, GLbyte green, GLbyte blue, GLbyte alpha));
TWIGL_DONT_NEED (void, glColor4bv, (const GLbyte * v));
TWIGL_DONT_NEED (void, glColor4d, (GLdouble red, GLdouble green, GLdouble blue, GLdouble alpha));
TWIGL_DONT_NEED (void, glColor4dv, (const GLdouble * v));
TWIGL_NEED (void, glColor4f, (GLfloat red, GLfloat green, GLfloat blue, GLfloat alpha));
TWIGL_NEED (void, glColor4fv, (const GLfloat * v));
TWIGL_DONT_NEED (void, glColor4i, (GLint red, GLint green, GLint blue, GLint alpha));
TWIGL_DONT_NEED (void, glColor4iv, (const GLint * v));
TWIGL_DONT_NEED (void, glColor4s, (GLshort red, GLshort green, GLshort blue, GLshort alpha));
TWIGL_DONT_NEED (void, glColor4sv, (const GLshort * v));
TWIGL_NEED (void, glColor4ub, (GLubyte red, GLubyte green, GLubyte blue, GLubyte alpha));
TWIGL_NEED (void, glColor4ubv, (const GLubyte * v));
TWIGL_DONT_NEED (void, glColor4ui, (GLuint red, GLuint green, GLuint blue, GLuint alpha));
TWIGL_DONT_NEED (void, glColor4uiv, (const GLuint * v));
TWIGL_DONT_NEED (void, glColor4us, (GLushort red, GLushort green, GLushort blue, GLushort alpha));
TWIGL_DONT_NEED (void, glColor4usv, (const GLushort * v));
TWIGL_DONT_NEED (void, glColorMask, (GLboolean red, GLboolean green, GLboolean blue, GLboolean alpha));
TWIGL_DONT_NEED (void, glColorMaterial, (GLenum face, GLenum mode));
TWIGL_DONT_NEED (void, glColorPointer, (GLint size, GLenum type, GLsizei stride, const GLvoid * ptr));
TWIGL_DONT_NEED (void, glColorPointerEXT, (GLint size, GLenum type, GLsizei stride, GLsizei count, const GLvoid * ptr));
TWIGL_DONT_NEED (void, glColorSubTable, (GLenum target, GLsizei start, GLsizei count, GLenum format, GLenum type, const GLvoid * data));
TWIGL_DONT_NEED (void, glColorSubTableEXT, (GLenum target, GLsizei start, GLsizei count, GLenum format, GLenum type, const GLvoid * data));
TWIGL_DONT_NEED (void, glColorTable, (GLenum target, GLenum internalformat, GLsizei width, GLenum format, GLenum type, const GLvoid * table));
TWIGL_DONT_NEED (void, glColorTableEXT, (GLenum target, GLenum internalformat, GLsizei width, GLenum format, GLenum type, const GLvoid * table));
TWIGL_DONT_NEED (void, glColorTableParameterfv, (GLenum target, GLenum pname, const GLfloat * params));
TWIGL_DONT_NEED (void, glColorTableParameteriv, (GLenum target, GLenum pname, const GLint * params));
TWIGL_DONT_NEED (void, glConvolutionFilter1D, (GLenum target, GLenum internalformat, GLsizei width, GLenum format, GLenum type, const GLvoid * image));
TWIGL_DONT_NEED (void, glConvolutionFilter2D, (GLenum target, GLenum internalformat, GLsizei width, GLsizei height, GLenum format, GLenum type, const GLvoid * image));
TWIGL_DONT_NEED (void, glConvolutionParameterf, (GLenum target, GLenum pname, GLfloat params));
TWIGL_DONT_NEED (void, glConvolutionParameterfv, (GLenum target, GLenum pname, const GLfloat * params));
TWIGL_DONT_NEED (void, glConvolutionParameteri, (GLenum target, GLenum pname, GLint params));
TWIGL_DONT_NEED (void, glConvolutionParameteriv, (GLenum target, GLenum pname, const GLint * params));
TWIGL_DONT_NEED (void, glCopyColorSubTable, (GLenum target, GLsizei start, GLint x, GLint y, GLsizei width));
TWIGL_DONT_NEED (void, glCopyColorTable, (GLenum target, GLenum internalformat, GLint x, GLint y, GLsizei width));
TWIGL_DONT_NEED (void, glCopyConvolutionFilter1D, (GLenum target, GLenum internalformat, GLint x, GLint y, GLsizei width));
TWIGL_DONT_NEED (void, glCopyConvolutionFilter2D, (GLenum target, GLenum internalformat, GLint x, GLint y, GLsizei width, GLsizei height));
TWIGL_DONT_NEED (void, glCopyPixels, (GLint x, GLint y, GLsizei width, GLsizei height, GLenum type));
TWIGL_DONT_NEED (void, glCopyTexImage1D, (GLenum target, GLint level, GLenum internalformat, GLint x, GLint y, GLsizei width, GLint border));
TWIGL_DONT_NEED (void, glCopyTexImage2D, (GLenum target, GLint level, GLenum internalformat, GLint x, GLint y, GLsizei width, GLsizei height, GLint border));
TWIGL_DONT_NEED (void, glCopyTexSubImage1D, (GLenum target, GLint level, GLint xoffset, GLint x, GLint y, GLsizei width));
TWIGL_DONT_NEED (void, glCopyTexSubImage2D, (GLenum target, GLint level, GLint xoffset, GLint yoffset, GLint x, GLint y, GLsizei width, GLsizei height));
TWIGL_DONT_NEED (void, glCopyTexSubImage3D, (GLenum target, GLint level, GLint xoffset, GLint yoffset, GLint zoffset, GLint x, GLint y, GLsizei width, GLsizei height));
TWIGL_DONT_NEED (void, glCopyTexSubImage3DEXT, (GLenum target, GLint level, GLint xoffset, GLint yoffset, GLint zoffset, GLint x, GLint y, GLsizei width, GLsizei height));
TWIGL_NEED (void, glCullFace, (GLenum mode));
TWIGL_DONT_NEED (void, glDeleteLists, (GLuint list, GLsizei range));
TWIGL_DONT_NEED (void, glDeleteTextures, (GLsizei n, const GLuint * textures));
TWIGL_DONT_NEED (void, glDeleteTexturesEXT, (GLsizei n, const GLuint * textures));
TWIGL_NEED (void, glDepthFunc, (GLenum func));
TWIGL_NEED (void, glDepthMask, (GLboolean flag));
TWIGL_NEED (void, glDepthRange, (GLclampd near_val, GLclampd far_val));
TWIGL_NEED (void, glDisable, (GLenum cap));
TWIGL_DONT_NEED (void, glDisableClientState, (GLenum cap));
TWIGL_DONT_NEED (void, glDisableTraceMESA, (GLbitfield mask));
TWIGL_DONT_NEED (void, glDrawArrays, (GLenum mode, GLint first, GLsizei count));
TWIGL_DONT_NEED (void, glDrawArraysEXT, (GLenum mode, GLint first, GLsizei count));
TWIGL_NEED (void, glDrawBuffer, (GLenum mode));
TWIGL_DONT_NEED (void, glDrawElements, (GLenum mode, GLsizei count, GLenum type, const GLvoid * indices));
TWIGL_DONT_NEED (void, glDrawPixels, (GLsizei width, GLsizei height, GLenum format, GLenum type, const GLvoid * pixels));
TWIGL_DONT_NEED (void, glDrawRangeElements, (GLenum mode, GLuint start, GLuint end, GLsizei count, GLenum type, const GLvoid * indices));
TWIGL_DONT_NEED (void, glEdgeFlag, (GLboolean flag));
TWIGL_DONT_NEED (void, glEdgeFlagPointer, (GLsizei stride, const GLvoid * ptr));
TWIGL_DONT_NEED (void, glEdgeFlagPointerEXT, (GLsizei stride, GLsizei count, const GLboolean * ptr));
TWIGL_DONT_NEED (void, glEdgeFlagv, (const GLboolean * flag));
TWIGL_NEED (void, glEnable, (GLenum cap));
TWIGL_DONT_NEED (void, glEnableClientState, (GLenum cap));
TWIGL_DONT_NEED (void, glEnableTraceMESA, (GLbitfield mask));
TWIGL_NEED (void, glEnd, (void));
TWIGL_DONT_NEED (void, glEndList, (void));
TWIGL_DONT_NEED (void, glEndTraceMESA, (void));
TWIGL_DONT_NEED (void, glEvalCoord1d, (GLdouble u));
TWIGL_DONT_NEED (void, glEvalCoord1dv, (const GLdouble * u));
TWIGL_DONT_NEED (void, glEvalCoord1f, (GLfloat u));
TWIGL_DONT_NEED (void, glEvalCoord1fv, (const GLfloat * u));
TWIGL_DONT_NEED (void, glEvalCoord2d, (GLdouble u, GLdouble v));
TWIGL_DONT_NEED (void, glEvalCoord2dv, (const GLdouble * u));
TWIGL_DONT_NEED (void, glEvalCoord2f, (GLfloat u, GLfloat v));
TWIGL_DONT_NEED (void, glEvalCoord2fv, (const GLfloat * u));
TWIGL_DONT_NEED (void, glEvalMesh1, (GLenum mode, GLint i1, GLint i2));
TWIGL_DONT_NEED (void, glEvalMesh2, (GLenum mode, GLint i1, GLint i2, GLint j1, GLint j2));
TWIGL_DONT_NEED (void, glEvalPoint1, (GLint i));
TWIGL_DONT_NEED (void, glEvalPoint2, (GLint i, GLint j));
TWIGL_DONT_NEED (void, glFeedbackBuffer, (GLsizei size, GLenum type, GLfloat * buffer));
TWIGL_NEED (void, glFinish, (void));
TWIGL_DONT_NEED (void, glFlush, (void));
TWIGL_DONT_NEED (void, glFogf, (GLenum pname, GLfloat param));
TWIGL_DONT_NEED (void, glFogfv, (GLenum pname, const GLfloat * params));
TWIGL_DONT_NEED (void, glFogi, (GLenum pname, GLint param));
TWIGL_DONT_NEED (void, glFogiv, (GLenum pname, const GLint * params));
TWIGL_DONT_NEED (void, glFrontFace, (GLenum mode));
TWIGL_NEED (void, glFrustum, (GLdouble left, GLdouble right, GLdouble bottom, GLdouble top, GLdouble near_val, GLdouble far_val));
TWIGL_DONT_NEED (GLuint, glGenLists, (GLsizei range));
TWIGL_DONT_NEED (void, glGenTextures, (GLsizei n, GLuint * textures));
TWIGL_DONT_NEED (void, glGenTexturesEXT, (GLsizei n, GLuint * textures));
TWIGL_DONT_NEED (void, glGetBooleanv, (GLenum pname, GLboolean * params));
TWIGL_DONT_NEED (void, glGetClipPlane, (GLenum plane, GLdouble * equation));
TWIGL_DONT_NEED (void, glGetColorTable, (GLenum target, GLenum format, GLenum type, GLvoid * table));
TWIGL_DONT_NEED (void, glGetColorTableEXT, (GLenum target, GLenum format, GLenum type, GLvoid * table));
TWIGL_DONT_NEED (void, glGetColorTableParameterfv, (GLenum target, GLenum pname, GLfloat * params));
TWIGL_DONT_NEED (void, glGetColorTableParameterfvEXT, (GLenum target, GLenum pname, GLfloat * params));
TWIGL_DONT_NEED (void, glGetColorTableParameteriv, (GLenum target, GLenum pname, GLint * params));
TWIGL_DONT_NEED (void, glGetColorTableParameterivEXT, (GLenum target, GLenum pname, GLint * params));
TWIGL_DONT_NEED (void, glGetConvolutionFilter, (GLenum target, GLenum format, GLenum type, GLvoid * image));
TWIGL_DONT_NEED (void, glGetConvolutionParameterfv, (GLenum target, GLenum pname, GLfloat * params));
TWIGL_DONT_NEED (void, glGetConvolutionParameteriv, (GLenum target, GLenum pname, GLint * params));
TWIGL_DONT_NEED (void, glGetDoublev, (GLenum pname, GLdouble * params));
TWIGL_DONT_NEED (GLenum, glGetError, (void));
TWIGL_NEED (void, glGetFloatv, (GLenum pname, GLfloat * params));
TWIGL_DONT_NEED (void, glGetHistogram, (GLenum target, GLboolean reset, GLenum format, GLenum type, GLvoid * values));
TWIGL_DONT_NEED (void, glGetHistogramParameterfv, (GLenum target, GLenum pname, GLfloat * params));
TWIGL_DONT_NEED (void, glGetHistogramParameteriv, (GLenum target, GLenum pname, GLint * params));
TWIGL_DONT_NEED (void, glGetIntegerv, (GLenum pname, GLint * params));
TWIGL_DONT_NEED (void, glGetLightfv, (GLenum light, GLenum pname, GLfloat * params));
TWIGL_DONT_NEED (void, glGetLightiv, (GLenum light, GLenum pname, GLint * params));
TWIGL_DONT_NEED (void, glGetMapdv, (GLenum target, GLenum query, GLdouble * v));
TWIGL_DONT_NEED (void, glGetMapfv, (GLenum target, GLenum query, GLfloat * v));
TWIGL_DONT_NEED (void, glGetMapiv, (GLenum target, GLenum query, GLint * v));
TWIGL_DONT_NEED (void, glGetMaterialfv, (GLenum face, GLenum pname, GLfloat * params));
TWIGL_DONT_NEED (void, glGetMaterialiv, (GLenum face, GLenum pname, GLint * params));
TWIGL_DONT_NEED (void, glGetMinmax, (GLenum target, GLboolean reset, GLenum format, GLenum types, GLvoid * values));
TWIGL_DONT_NEED (void, glGetMinmaxParameterfv, (GLenum target, GLenum pname, GLfloat * params));
TWIGL_DONT_NEED (void, glGetMinmaxParameteriv, (GLenum target, GLenum pname, GLint * params));
TWIGL_DONT_NEED (void, glGetPixelMapfv, (GLenum map, GLfloat * values));
TWIGL_DONT_NEED (void, glGetPixelMapuiv, (GLenum map, GLuint * values));
TWIGL_DONT_NEED (void, glGetPixelMapusv, (GLenum map, GLushort * values));
TWIGL_DONT_NEED (void, glGetPointerv, (GLenum pname, GLvoid ** params));
TWIGL_DONT_NEED (void, glGetPointervEXT, (GLenum pname, GLvoid ** params));
TWIGL_DONT_NEED (void, glGetPolygonStipple, (GLubyte * mask));
TWIGL_DONT_NEED (void, glGetSeparableFilter, (GLenum target, GLenum format, GLenum type, GLvoid * row, GLvoid * column, GLvoid * span));
TWIGL_NEED (const GLubyte *, glGetString, (GLenum name));
TWIGL_DONT_NEED (void, glGetTexEnvfv, (GLenum target, GLenum pname, GLfloat * params));
TWIGL_DONT_NEED (void, glGetTexEnviv, (GLenum target, GLenum pname, GLint * params));
TWIGL_DONT_NEED (void, glGetTexGendv, (GLenum coord, GLenum pname, GLdouble * params));
TWIGL_DONT_NEED (void, glGetTexGenfv, (GLenum coord, GLenum pname, GLfloat * params));
TWIGL_DONT_NEED (void, glGetTexGeniv, (GLenum coord, GLenum pname, GLint * params));
TWIGL_DONT_NEED (void, glGetTexImage, (GLenum target, GLint level, GLenum format, GLenum type, GLvoid * pixels));
TWIGL_DONT_NEED (void, glGetTexLevelParameterfv, (GLenum target, GLint level, GLenum pname, GLfloat * params));
TWIGL_DONT_NEED (void, glGetTexLevelParameteriv, (GLenum target, GLint level, GLenum pname, GLint * params));
TWIGL_DONT_NEED (void, glGetTexParameterfv, (GLenum target, GLenum pname, GLfloat * params));
TWIGL_DONT_NEED (void, glGetTexParameteriv, (GLenum target, GLenum pname, GLint * params));
TWIGL_NEED (void, glHint, (GLenum target, GLenum mode));
TWIGL_DONT_NEED (void, glHistogram, (GLenum target, GLsizei width, GLenum internalformat, GLboolean sink));
TWIGL_DONT_NEED (void, glIndexMask, (GLuint mask));
TWIGL_DONT_NEED (void, glIndexPointer, (GLenum type, GLsizei stride, const GLvoid * ptr));
TWIGL_DONT_NEED (void, glIndexPointerEXT, (GLenum type, GLsizei stride, GLsizei count, const GLvoid * ptr));
TWIGL_DONT_NEED (void, glIndexd, (GLdouble c));
TWIGL_DONT_NEED (void, glIndexdv, (const GLdouble * c));
TWIGL_DONT_NEED (void, glIndexf, (GLfloat c));
TWIGL_DONT_NEED (void, glIndexfv, (const GLfloat * c));
TWIGL_DONT_NEED (void, glIndexi, (GLint c));
TWIGL_DONT_NEED (void, glIndexiv, (const GLint * c));
TWIGL_DONT_NEED (void, glIndexs, (GLshort c));
TWIGL_DONT_NEED (void, glIndexsv, (const GLshort * c));
TWIGL_DONT_NEED (void, glIndexub, (GLubyte c));
TWIGL_DONT_NEED (void, glIndexubv, (const GLubyte * c));
TWIGL_DONT_NEED (void, glInitNames, (void));
TWIGL_DONT_NEED (void, glInterleavedArrays, (GLenum format, GLsizei stride, const GLvoid * pointer));
TWIGL_NEED (GLboolean, glIsEnabled, (GLenum cap));
TWIGL_DONT_NEED (GLboolean, glIsList, (GLuint list));
TWIGL_DONT_NEED (GLboolean, glIsTexture, (GLuint texture));
TWIGL_DONT_NEED (GLboolean, glIsTextureEXT, (GLuint texture));
TWIGL_DONT_NEED (void, glLightModelf, (GLenum pname, GLfloat param));
TWIGL_DONT_NEED (void, glLightModelfv, (GLenum pname, const GLfloat * params));
TWIGL_DONT_NEED (void, glLightModeli, (GLenum pname, GLint param));
TWIGL_DONT_NEED (void, glLightModeliv, (GLenum pname, const GLint * params));
TWIGL_DONT_NEED (void, glLightf, (GLenum light, GLenum pname, GLfloat param));
TWIGL_DONT_NEED (void, glLightfv, (GLenum light, GLenum pname, const GLfloat * params));
TWIGL_DONT_NEED (void, glLighti, (GLenum light, GLenum pname, GLint param));
TWIGL_DONT_NEED (void, glLightiv, (GLenum light, GLenum pname, const GLint * params));
TWIGL_DONT_NEED (void, glLineStipple, (GLint factor, GLushort pattern));
TWIGL_DONT_NEED (void, glLineWidth, (GLfloat width));
TWIGL_DONT_NEED (void, glListBase, (GLuint base));
TWIGL_NEED (void, glLoadIdentity, (void));
TWIGL_DONT_NEED (void, glLoadMatrixd, (const GLdouble * m));
TWIGL_NEED (void, glLoadMatrixf, (const GLfloat * m));
TWIGL_DONT_NEED (void, glLoadName, (GLuint name));
TWIGL_DONT_NEED (void, glLockArraysEXT, (GLint first, GLsizei count));
TWIGL_DONT_NEED (void, glLogicOp, (GLenum opcode));
TWIGL_DONT_NEED (void, glMap1d, (GLenum target, GLdouble u1, GLdouble u2, GLint stride, GLint order, const GLdouble * points));
TWIGL_DONT_NEED (void, glMap1f, (GLenum target, GLfloat u1, GLfloat u2, GLint stride, GLint order, const GLfloat * points));
TWIGL_DONT_NEED (void, glMap2d, (GLenum target, GLdouble u1, GLdouble u2, GLint ustride, GLint uorder, GLdouble v1, GLdouble v2, GLint vstride, GLint vorder, const GLdouble * points));
TWIGL_DONT_NEED (void, glMap2f, (GLenum target, GLfloat u1, GLfloat u2, GLint ustride, GLint uorder, GLfloat v1, GLfloat v2, GLint vstride, GLint vorder, const GLfloat * points));
TWIGL_DONT_NEED (void, glMapGrid1d, (GLint un, GLdouble u1, GLdouble u2));
TWIGL_DONT_NEED (void, glMapGrid1f, (GLint un, GLfloat u1, GLfloat u2));
TWIGL_DONT_NEED (void, glMapGrid2d, (GLint un, GLdouble u1, GLdouble u2, GLint vn, GLdouble v1, GLdouble v2));
TWIGL_DONT_NEED (void, glMapGrid2f, (GLint un, GLfloat u1, GLfloat u2, GLint vn, GLfloat v1, GLfloat v2));
TWIGL_DONT_NEED (void, glMaterialf, (GLenum face, GLenum pname, GLfloat param));
TWIGL_DONT_NEED (void, glMaterialfv, (GLenum face, GLenum pname, const GLfloat * params));
TWIGL_DONT_NEED (void, glMateriali, (GLenum face, GLenum pname, GLint param));
TWIGL_DONT_NEED (void, glMaterialiv, (GLenum face, GLenum pname, const GLint * params));
TWIGL_NEED (void, glMatrixMode, (GLenum mode));
TWIGL_DONT_NEED (void, glMinmax, (GLenum target, GLenum internalformat, GLboolean sink));
TWIGL_DONT_NEED (void, glMultMatrixd, (const GLdouble * m));
TWIGL_DONT_NEED (void, glMultMatrixf, (const GLfloat * m));
TWIGL_DONT_NEED (void, glMultiTexCoord1dARB, (GLenum target, GLdouble s));
TWIGL_DONT_NEED (void, glMultiTexCoord1dvARB, (GLenum target, const GLdouble * v));
TWIGL_DONT_NEED (void, glMultiTexCoord1fARB, (GLenum target, GLfloat s));
TWIGL_DONT_NEED (void, glMultiTexCoord1fvARB, (GLenum target, const GLfloat * v));
TWIGL_DONT_NEED (void, glMultiTexCoord1iARB, (GLenum target, GLint s));
TWIGL_DONT_NEED (void, glMultiTexCoord1ivARB, (GLenum target, const GLint * v));
TWIGL_DONT_NEED (void, glMultiTexCoord1sARB, (GLenum target, GLshort s));
TWIGL_DONT_NEED (void, glMultiTexCoord1svARB, (GLenum target, const GLshort * v));
TWIGL_DONT_NEED (void, glMultiTexCoord2dARB, (GLenum target, GLdouble s, GLdouble t));
TWIGL_DONT_NEED (void, glMultiTexCoord2dvARB, (GLenum target, const GLdouble * v));
TWIGL_DONT_NEED (void, glMultiTexCoord2fARB, (GLenum target, GLfloat s, GLfloat t));
TWIGL_DONT_NEED (void, glMultiTexCoord2fvARB, (GLenum target, const GLfloat * v));
TWIGL_DONT_NEED (void, glMultiTexCoord2iARB, (GLenum target, GLint s, GLint t));
TWIGL_DONT_NEED (void, glMultiTexCoord2ivARB, (GLenum target, const GLint * v));
TWIGL_DONT_NEED (void, glMultiTexCoord2sARB, (GLenum target, GLshort s, GLshort t));
TWIGL_DONT_NEED (void, glMultiTexCoord2svARB, (GLenum target, const GLshort * v));
TWIGL_DONT_NEED (void, glMultiTexCoord3dARB, (GLenum target, GLdouble s, GLdouble t, GLdouble r));
TWIGL_DONT_NEED (void, glMultiTexCoord3dvARB, (GLenum target, const GLdouble * v));
TWIGL_DONT_NEED (void, glMultiTexCoord3fARB, (GLenum target, GLfloat s, GLfloat t, GLfloat r));
TWIGL_DONT_NEED (void, glMultiTexCoord3fvARB, (GLenum target, const GLfloat * v));
TWIGL_DONT_NEED (void, glMultiTexCoord3iARB, (GLenum target, GLint s, GLint t, GLint r));
TWIGL_DONT_NEED (void, glMultiTexCoord3ivARB, (GLenum target, const GLint * v));
TWIGL_DONT_NEED (void, glMultiTexCoord3sARB, (GLenum target, GLshort s, GLshort t, GLshort r));
TWIGL_DONT_NEED (void, glMultiTexCoord3svARB, (GLenum target, const GLshort * v));
TWIGL_DONT_NEED (void, glMultiTexCoord4dARB, (GLenum target, GLdouble s, GLdouble t, GLdouble r, GLdouble q));
TWIGL_DONT_NEED (void, glMultiTexCoord4dvARB, (GLenum target, const GLdouble * v));
TWIGL_DONT_NEED (void, glMultiTexCoord4fARB, (GLenum target, GLfloat s, GLfloat t, GLfloat r, GLfloat q));
TWIGL_DONT_NEED (void, glMultiTexCoord4fvARB, (GLenum target, const GLfloat * v));
TWIGL_DONT_NEED (void, glMultiTexCoord4iARB, (GLenum target, GLint s, GLint t, GLint r, GLint q));
TWIGL_DONT_NEED (void, glMultiTexCoord4ivARB, (GLenum target, const GLint * v));
TWIGL_DONT_NEED (void, glMultiTexCoord4sARB, (GLenum target, GLshort s, GLshort t, GLshort r, GLshort q));
TWIGL_DONT_NEED (void, glMultiTexCoord4svARB, (GLenum target, const GLshort * v));
TWIGL_DONT_NEED (void, glNewList, (GLuint list, GLenum mode));
TWIGL_DONT_NEED (void, glNewTraceMESA, (GLbitfield mask, const GLubyte * traceName));
TWIGL_DONT_NEED (void, glNormal3b, (GLbyte nx, GLbyte ny, GLbyte nz));
TWIGL_DONT_NEED (void, glNormal3bv, (const GLbyte * v));
TWIGL_DONT_NEED (void, glNormal3d, (GLdouble nx, GLdouble ny, GLdouble nz));
TWIGL_DONT_NEED (void, glNormal3dv, (const GLdouble * v));
TWIGL_DONT_NEED (void, glNormal3f, (GLfloat nx, GLfloat ny, GLfloat nz));
TWIGL_DONT_NEED (void, glNormal3fv, (const GLfloat * v));
TWIGL_DONT_NEED (void, glNormal3i, (GLint nx, GLint ny, GLint nz));
TWIGL_DONT_NEED (void, glNormal3iv, (const GLint * v));
TWIGL_DONT_NEED (void, glNormal3s, (GLshort nx, GLshort ny, GLshort nz));
TWIGL_DONT_NEED (void, glNormal3sv, (const GLshort * v));
TWIGL_DONT_NEED (void, glNormalPointer, (GLenum type, GLsizei stride, const GLvoid * ptr));
TWIGL_DONT_NEED (void, glNormalPointerEXT, (GLenum type, GLsizei stride, GLsizei count, const GLvoid * ptr));
TWIGL_NEED (void, glOrtho, (GLdouble left, GLdouble right, GLdouble bottom, GLdouble top, GLdouble near_val, GLdouble far_val));
TWIGL_DONT_NEED (void, glPassThrough, (GLfloat token));
TWIGL_DONT_NEED (void, glPixelMapfv, (GLenum map, GLint mapsize, const GLfloat * values));
TWIGL_DONT_NEED (void, glPixelMapuiv, (GLenum map, GLint mapsize, const GLuint * values));
TWIGL_DONT_NEED (void, glPixelMapusv, (GLenum map, GLint mapsize, const GLushort * values));
TWIGL_DONT_NEED (void, glPixelStoref, (GLenum pname, GLfloat param));
TWIGL_DONT_NEED (void, glPixelStorei, (GLenum pname, GLint param));
TWIGL_DONT_NEED (void, glPixelTransferf, (GLenum pname, GLfloat param));
TWIGL_DONT_NEED (void, glPixelTransferi, (GLenum pname, GLint param));
TWIGL_DONT_NEED (void, glPixelZoom, (GLfloat xfactor, GLfloat yfactor));
TWIGL_DONT_NEED (void, glPointParameterfEXT, (GLenum pname, GLfloat param));
TWIGL_DONT_NEED (void, glPointParameterfSGIS, (GLenum pname, GLfloat param));
TWIGL_DONT_NEED (void, glPointParameterfvEXT, (GLenum pname, const GLfloat * params));
TWIGL_DONT_NEED (void, glPointParameterfvSGIS, (GLenum pname, const GLfloat * params));
TWIGL_DONT_NEED (void, glPointSize, (GLfloat size));
TWIGL_NEED (void, glPolygonMode, (GLenum face, GLenum mode));
TWIGL_DONT_NEED (void, glPolygonOffset, (GLfloat factor, GLfloat units));
TWIGL_DONT_NEED (void, glPolygonOffsetEXT, (GLfloat factor, GLfloat bias));
TWIGL_DONT_NEED (void, glPolygonStipple, (const GLubyte * mask));
TWIGL_DONT_NEED (void, glPopAttrib, (void));
TWIGL_DONT_NEED (void, glPopClientAttrib, (void));
TWIGL_NEED (void, glPopMatrix, (void));
TWIGL_DONT_NEED (void, glPopName, (void));
TWIGL_DONT_NEED (void, glPrioritizeTextures, (GLsizei n, const GLuint * textures, const GLclampf * priorities));
TWIGL_DONT_NEED (void, glPrioritizeTexturesEXT, (GLsizei n, const GLuint * textures, const GLclampf * priorities));
TWIGL_DONT_NEED (void, glPushAttrib, (GLbitfield mask));
TWIGL_DONT_NEED (void, glPushClientAttrib, (GLbitfield mask));
TWIGL_NEED (void, glPushMatrix, (void));
TWIGL_DONT_NEED (void, glPushName, (GLuint name));
TWIGL_DONT_NEED (void, glRasterPos2d, (GLdouble x, GLdouble y));
TWIGL_DONT_NEED (void, glRasterPos2dv, (const GLdouble * v));
TWIGL_DONT_NEED (void, glRasterPos2f, (GLfloat x, GLfloat y));
TWIGL_DONT_NEED (void, glRasterPos2fv, (const GLfloat * v));
TWIGL_DONT_NEED (void, glRasterPos2i, (GLint x, GLint y));
TWIGL_DONT_NEED (void, glRasterPos2iv, (const GLint * v));
TWIGL_DONT_NEED (void, glRasterPos2s, (GLshort x, GLshort y));
TWIGL_DONT_NEED (void, glRasterPos2sv, (const GLshort * v));
TWIGL_DONT_NEED (void, glRasterPos3d, (GLdouble x, GLdouble y, GLdouble z));
TWIGL_DONT_NEED (void, glRasterPos3dv, (const GLdouble * v));
TWIGL_DONT_NEED (void, glRasterPos3f, (GLfloat x, GLfloat y, GLfloat z));
TWIGL_DONT_NEED (void, glRasterPos3fv, (const GLfloat * v));
TWIGL_DONT_NEED (void, glRasterPos3i, (GLint x, GLint y, GLint z));
TWIGL_DONT_NEED (void, glRasterPos3iv, (const GLint * v));
TWIGL_DONT_NEED (void, glRasterPos3s, (GLshort x, GLshort y, GLshort z));
TWIGL_DONT_NEED (void, glRasterPos3sv, (const GLshort * v));
TWIGL_DONT_NEED (void, glRasterPos4d, (GLdouble x, GLdouble y, GLdouble z, GLdouble w));
TWIGL_DONT_NEED (void, glRasterPos4dv, (const GLdouble * v));
TWIGL_DONT_NEED (void, glRasterPos4f, (GLfloat x, GLfloat y, GLfloat z, GLfloat w));
TWIGL_DONT_NEED (void, glRasterPos4fv, (const GLfloat * v));
TWIGL_DONT_NEED (void, glRasterPos4i, (GLint x, GLint y, GLint z, GLint w));
TWIGL_DONT_NEED (void, glRasterPos4iv, (const GLint * v));
TWIGL_DONT_NEED (void, glRasterPos4s, (GLshort x, GLshort y, GLshort z, GLshort w));
TWIGL_DONT_NEED (void, glRasterPos4sv, (const GLshort * v));
TWIGL_NEED (void, glReadBuffer, (GLenum mode));
TWIGL_NEED (void, glReadPixels, (GLint x, GLint y, GLsizei width, GLsizei height, GLenum format, GLenum type, GLvoid * pixels));
TWIGL_DONT_NEED (void, glRectd, (GLdouble x1, GLdouble y1, GLdouble x2, GLdouble y2));
TWIGL_DONT_NEED (void, glRectdv, (const GLdouble * v1, const GLdouble * v2));
TWIGL_DONT_NEED (void, glRectf, (GLfloat x1, GLfloat y1, GLfloat x2, GLfloat y2));
TWIGL_DONT_NEED (void, glRectfv, (const GLfloat * v1, const GLfloat * v2));
TWIGL_DONT_NEED (void, glRecti, (GLint x1, GLint y1, GLint x2, GLint y2));
TWIGL_DONT_NEED (void, glRectiv, (const GLint * v1, const GLint * v2));
TWIGL_DONT_NEED (void, glRects, (GLshort x1, GLshort y1, GLshort x2, GLshort y2));
TWIGL_DONT_NEED (void, glRectsv, (const GLshort * v1, const GLshort * v2));
TWIGL_DONT_NEED (GLint, glRenderMode, (GLenum mode));
TWIGL_DONT_NEED (void, glResetHistogram, (GLenum target));
TWIGL_DONT_NEED (void, glResetMinmax, (GLenum target));
TWIGL_DONT_NEED (void, glResizeBuffersMESA, (void));
TWIGL_DONT_NEED (void, glRotated, (GLdouble angle, GLdouble x, GLdouble y, GLdouble z));
TWIGL_NEED (void, glRotatef, (GLfloat angle, GLfloat x, GLfloat y, GLfloat z));
TWIGL_DONT_NEED (void, glScaled, (GLdouble x, GLdouble y, GLdouble z));
TWIGL_NEED (void, glScalef, (GLfloat x, GLfloat y, GLfloat z));
TWIGL_DONT_NEED (void, glScissor, (GLint x, GLint y, GLsizei width, GLsizei height));
TWIGL_DONT_NEED (void, glSelectBuffer, (GLsizei size, GLuint * buffer));
TWIGL_DONT_NEED (void, glSeparableFilter2D, (GLenum target, GLenum internalformat, GLsizei width, GLsizei height, GLenum format, GLenum type, const GLvoid * row, const GLvoid * column));
TWIGL_NEED (void, glShadeModel, (GLenum mode));
TWIGL_DONT_NEED (void, glStencilFunc, (GLenum func, GLint ref, GLuint mask));
TWIGL_DONT_NEED (void, glStencilMask, (GLuint mask));
TWIGL_DONT_NEED (void, glStencilOp, (GLenum fail, GLenum zfail, GLenum zpass));
TWIGL_DONT_NEED (void, glTexCoord1d, (GLdouble s));
TWIGL_DONT_NEED (void, glTexCoord1dv, (const GLdouble * v));
TWIGL_DONT_NEED (void, glTexCoord1f, (GLfloat s));
TWIGL_DONT_NEED (void, glTexCoord1fv, (const GLfloat * v));
TWIGL_DONT_NEED (void, glTexCoord1i, (GLint s));
TWIGL_DONT_NEED (void, glTexCoord1iv, (const GLint * v));
TWIGL_DONT_NEED (void, glTexCoord1s, (GLshort s));
TWIGL_DONT_NEED (void, glTexCoord1sv, (const GLshort * v));
TWIGL_DONT_NEED (void, glTexCoord2d, (GLdouble s, GLdouble t));
TWIGL_DONT_NEED (void, glTexCoord2dv, (const GLdouble * v));
TWIGL_NEED (void, glTexCoord2f, (GLfloat s, GLfloat t));
TWIGL_NEED (void, glTexCoord2fv, (const GLfloat * v));
TWIGL_DONT_NEED (void, glTexCoord2i, (GLint s, GLint t));
TWIGL_DONT_NEED (void, glTexCoord2iv, (const GLint * v));
TWIGL_DONT_NEED (void, glTexCoord2s, (GLshort s, GLshort t));
TWIGL_DONT_NEED (void, glTexCoord2sv, (const GLshort * v));
TWIGL_DONT_NEED (void, glTexCoord3d, (GLdouble s, GLdouble t, GLdouble r));
TWIGL_DONT_NEED (void, glTexCoord3dv, (const GLdouble * v));
TWIGL_DONT_NEED (void, glTexCoord3f, (GLfloat s, GLfloat t, GLfloat r));
TWIGL_DONT_NEED (void, glTexCoord3fv, (const GLfloat * v));
TWIGL_DONT_NEED (void, glTexCoord3i, (GLint s, GLint t, GLint r));
TWIGL_DONT_NEED (void, glTexCoord3iv, (const GLint * v));
TWIGL_DONT_NEED (void, glTexCoord3s, (GLshort s, GLshort t, GLshort r));
TWIGL_DONT_NEED (void, glTexCoord3sv, (const GLshort * v));
TWIGL_DONT_NEED (void, glTexCoord4d, (GLdouble s, GLdouble t, GLdouble r, GLdouble q));
TWIGL_DONT_NEED (void, glTexCoord4dv, (const GLdouble * v));
TWIGL_DONT_NEED (void, glTexCoord4f, (GLfloat s, GLfloat t, GLfloat r, GLfloat q));
TWIGL_DONT_NEED (void, glTexCoord4fv, (const GLfloat * v));
TWIGL_DONT_NEED (void, glTexCoord4i, (GLint s, GLint t, GLint r, GLint q));
TWIGL_DONT_NEED (void, glTexCoord4iv, (const GLint * v));
TWIGL_DONT_NEED (void, glTexCoord4s, (GLshort s, GLshort t, GLshort r, GLshort q));
TWIGL_DONT_NEED (void, glTexCoord4sv, (const GLshort * v));
TWIGL_DONT_NEED (void, glTexCoordPointer, (GLint size, GLenum type, GLsizei stride, const GLvoid * ptr));
TWIGL_DONT_NEED (void, glTexCoordPointerEXT, (GLint size, GLenum type, GLsizei stride, GLsizei count, const GLvoid * ptr));
TWIGL_NEED (void, glTexEnvf, (GLenum target, GLenum pname, GLfloat param));
TWIGL_DONT_NEED (void, glTexEnvfv, (GLenum target, GLenum pname, const GLfloat * params));
TWIGL_DONT_NEED (void, glTexEnvi, (GLenum target, GLenum pname, GLint param));
TWIGL_DONT_NEED (void, glTexEnviv, (GLenum target, GLenum pname, const GLint * params));
TWIGL_DONT_NEED (void, glTexGend, (GLenum coord, GLenum pname, GLdouble param));
TWIGL_DONT_NEED (void, glTexGendv, (GLenum coord, GLenum pname, const GLdouble * params));
TWIGL_DONT_NEED (void, glTexGenf, (GLenum coord, GLenum pname, GLfloat param));
TWIGL_DONT_NEED (void, glTexGenfv, (GLenum coord, GLenum pname, const GLfloat * params));
TWIGL_DONT_NEED (void, glTexGeni, (GLenum coord, GLenum pname, GLint param));
TWIGL_DONT_NEED (void, glTexGeniv, (GLenum coord, GLenum pname, const GLint * params));
TWIGL_DONT_NEED (void, glTexImage1D, (GLenum target, GLint level, GLint internalFormat, GLsizei width, GLint border, GLenum format, GLenum type, const GLvoid * pixels));
TWIGL_NEED (void, glTexImage2D, (GLenum target, GLint level, GLint internalFormat, GLsizei width, GLsizei height, GLint border, GLenum format, GLenum type, const GLvoid * pixels));
TWIGL_DONT_NEED (void, glTexImage3D, (GLenum target, GLint level, GLenum internalFormat, GLsizei width, GLsizei height, GLsizei depth, GLint border, GLenum format, GLenum type, const GLvoid * pixels));
TWIGL_DONT_NEED (void, glTexImage3DEXT, (GLenum target, GLint level, GLenum internalFormat, GLsizei width, GLsizei height, GLsizei depth, GLint border, GLenum format, GLenum type, const GLvoid * pixels));
TWIGL_NEED (void, glTexParameterf, (GLenum target, GLenum pname, GLfloat param));
TWIGL_DONT_NEED (void, glTexParameterfv, (GLenum target, GLenum pname, const GLfloat * params));
TWIGL_DONT_NEED (void, glTexParameteri, (GLenum target, GLenum pname, GLint param));
TWIGL_DONT_NEED (void, glTexParameteriv, (GLenum target, GLenum pname, const GLint * params));
TWIGL_DONT_NEED (void, glTexSubImage1D, (GLenum target, GLint level, GLint xoffset, GLsizei width, GLenum format, GLenum type, const GLvoid * pixels));
TWIGL_NEED (void, glTexSubImage2D, (GLenum target, GLint level, GLint xoffset, GLint yoffset, GLsizei width, GLsizei height, GLenum format, GLenum type, const GLvoid * pixels));
TWIGL_DONT_NEED (void, glTexSubImage3D, (GLenum target, GLint level, GLint xoffset, GLint yoffset, GLint zoffset, GLsizei width, GLsizei height, GLsizei depth, GLenum format, GLenum type, const GLvoid * pixels));
TWIGL_DONT_NEED (void, glTexSubImage3DEXT, (GLenum target, GLint level, GLint xoffset, GLint yoffset, GLint zoffset, GLsizei width, GLsizei height, GLsizei depth, GLenum format, GLenum type, const GLvoid * pixels));
TWIGL_DONT_NEED (void, glTraceAssertAttribMESA, (GLbitfield attribMask));
TWIGL_DONT_NEED (void, glTraceCommentMESA, (const GLubyte * comment));
TWIGL_DONT_NEED (void, glTraceListMESA, (GLuint name, const GLubyte * comment));
TWIGL_DONT_NEED (void, glTracePointerMESA, (GLvoid * pointer, const GLubyte * comment));
TWIGL_DONT_NEED (void, glTracePointerRangeMESA, (const GLvoid * first, const GLvoid * last, const GLubyte * comment));
TWIGL_DONT_NEED (void, glTraceTextureMESA, (GLuint name, const GLubyte * comment));
TWIGL_DONT_NEED (void, glTranslated, (GLdouble x, GLdouble y, GLdouble z));
TWIGL_NEED (void, glTranslatef, (GLfloat x, GLfloat y, GLfloat z));
TWIGL_DONT_NEED (void, glUnlockArraysEXT, (void));
TWIGL_DONT_NEED (void, glVertex2d, (GLdouble x, GLdouble y));
TWIGL_DONT_NEED (void, glVertex2dv, (const GLdouble * v));
TWIGL_NEED (void, glVertex2f, (GLfloat x, GLfloat y));
TWIGL_DONT_NEED (void, glVertex2fv, (const GLfloat * v));
TWIGL_DONT_NEED (void, glVertex2i, (GLint x, GLint y));
TWIGL_DONT_NEED (void, glVertex2iv, (const GLint * v));
TWIGL_DONT_NEED (void, glVertex2s, (GLshort x, GLshort y));
TWIGL_DONT_NEED (void, glVertex2sv, (const GLshort * v));
TWIGL_DONT_NEED (void, glVertex3d, (GLdouble x, GLdouble y, GLdouble z));
TWIGL_DONT_NEED (void, glVertex3dv, (const GLdouble * v));
TWIGL_NEED (void, glVertex3f, (GLfloat x, GLfloat y, GLfloat z));
TWIGL_NEED (void, glVertex3fv, (const GLfloat * v));
TWIGL_DONT_NEED (void, glVertex3i, (GLint x, GLint y, GLint z));
TWIGL_DONT_NEED (void, glVertex3iv, (const GLint * v));
TWIGL_DONT_NEED (void, glVertex3s, (GLshort x, GLshort y, GLshort z));
TWIGL_DONT_NEED (void, glVertex3sv, (const GLshort * v));
TWIGL_DONT_NEED (void, glVertex4d, (GLdouble x, GLdouble y, GLdouble z, GLdouble w));
TWIGL_DONT_NEED (void, glVertex4dv, (const GLdouble * v));
TWIGL_DONT_NEED (void, glVertex4f, (GLfloat x, GLfloat y, GLfloat z, GLfloat w));
TWIGL_DONT_NEED (void, glVertex4fv, (const GLfloat * v));
TWIGL_DONT_NEED (void, glVertex4i, (GLint x, GLint y, GLint z, GLint w));
TWIGL_DONT_NEED (void, glVertex4iv, (const GLint * v));
TWIGL_DONT_NEED (void, glVertex4s, (GLshort x, GLshort y, GLshort z, GLshort w));
TWIGL_DONT_NEED (void, glVertex4sv, (const GLshort * v));
TWIGL_DONT_NEED (void, glVertexPointer, (GLint size, GLenum type, GLsizei stride, const GLvoid * ptr));
TWIGL_DONT_NEED (void, glVertexPointerEXT, (GLint size, GLenum type, GLsizei stride, GLsizei count, const GLvoid * ptr));
TWIGL_NEED (void, glViewport, (GLint x, GLint y, GLsizei width, GLsizei height));
TWIGL_DONT_NEED (void, glWindowPos2dMESA, (GLdouble x, GLdouble y));
TWIGL_DONT_NEED (void, glWindowPos2dvMESA, (const GLdouble * p));
TWIGL_DONT_NEED (void, glWindowPos2fMESA, (GLfloat x, GLfloat y));
TWIGL_DONT_NEED (void, glWindowPos2fvMESA, (const GLfloat * p));
TWIGL_DONT_NEED (void, glWindowPos2iMESA, (GLint x, GLint y));
TWIGL_DONT_NEED (void, glWindowPos2ivMESA, (const GLint * p));
TWIGL_DONT_NEED (void, glWindowPos2sMESA, (GLshort x, GLshort y));
TWIGL_DONT_NEED (void, glWindowPos2svMESA, (const GLshort * p));
TWIGL_DONT_NEED (void, glWindowPos3dMESA, (GLdouble x, GLdouble y, GLdouble z));
TWIGL_DONT_NEED (void, glWindowPos3dvMESA, (const GLdouble * p));
TWIGL_DONT_NEED (void, glWindowPos3fMESA, (GLfloat x, GLfloat y, GLfloat z));
TWIGL_DONT_NEED (void, glWindowPos3fvMESA, (const GLfloat * p));
TWIGL_DONT_NEED (void, glWindowPos3iMESA, (GLint x, GLint y, GLint z));
TWIGL_DONT_NEED (void, glWindowPos3ivMESA, (const GLint * p));
TWIGL_DONT_NEED (void, glWindowPos3sMESA, (GLshort x, GLshort y, GLshort z));
TWIGL_DONT_NEED (void, glWindowPos3svMESA, (const GLshort * p));
TWIGL_DONT_NEED (void, glWindowPos4dMESA, (GLdouble x, GLdouble y, GLdouble z, GLdouble w));
TWIGL_DONT_NEED (void, glWindowPos4dvMESA, (const GLdouble * p));
TWIGL_DONT_NEED (void, glWindowPos4fMESA, (GLfloat x, GLfloat y, GLfloat z, GLfloat w));
TWIGL_DONT_NEED (void, glWindowPos4fvMESA, (const GLfloat * p));
TWIGL_DONT_NEED (void, glWindowPos4iMESA, (GLint x, GLint y, GLint z, GLint w));
TWIGL_DONT_NEED (void, glWindowPos4ivMESA, (const GLint * p));
TWIGL_DONT_NEED (void, glWindowPos4sMESA, (GLshort x, GLshort y, GLshort z, GLshort w));
TWIGL_DONT_NEED (void, glWindowPos4svMESA, (const GLshort * p));

#ifdef UNDEF_TWIGL_DONT_NEED
#undef TWIGL_DONT_NEED
#endif

