#! /usr/bin/python

Import ("env")
env.Append (CPPPATH = ["#/src/client"])

client_headers = Split("""cclient.h console.h dlight.h hud.h keys.h
	teamplay.h""")

client_sources = Split("""cclient.c console.c dlight.c input.c hud.c keys.c
	teamplay.c""")

client_headers = ['#/src/client/'+e for e in client_headers]
client_sources = ['#/src/client/'+e for e in client_sources]

Export ("client_headers", "client_sources")
