#! /usr/bin/python

Import ("env")
#env.Append (CPPPATH = ["#/src/fs"])

fs_headers = Split("""bsp.h dir.h embedded.h embedded_data.h fs.h fs_hash.h
	fs_new.h pak.h rw_ops.h wad.h""")

fs_sources = Split("""bsp.c embedded.c fs.c fs_hash.c fs_new.c pak.c rw_ops.c
	wad.c""")
fs_sources.extend ([env['dir_mode'] + '.c'])

fs_headers = ['#/src/fs/'+e for e in fs_headers]
fs_sources = ['#/src/fs/'+e for e in fs_sources]

Export ("fs_headers", "fs_sources")
